// Generated by scripts/generate-galaxy-data.mjs from starbroken_wiki_dump/pages.jsonl.
// Do not edit by hand.

export const REGION_SIZE = 8192;
export const SECTOR_SIZE = 4096;
export const GALAXY_COLUMNS = 8;
export const GALAXY_ROWS = 8;
export const GALAXY_SIZE = REGION_SIZE * GALAXY_COLUMNS;
export const GENERATED_AT = "2026-06-28T05:28:33.528Z";
export const GENERATED_SOURCE = "https://wiki.starbroken.net/reference/galaxy-map-roster.html";

export const generatedRegions = [
  {
    "coord": "A1",
    "name": "Vega Reach",
    "slug": "vega-reach-r0",
    "zone": "CORE",
    "security": "Patrolled Lanes (CORE)",
    "col": 0,
    "row": 0,
    "xMin": 0,
    "zMin": 0,
    "xMax": 8192,
    "zMax": 8192,
    "sectors": [
      {
        "id": "NW",
        "xMin": 0,
        "zMin": 0,
        "xMax": 4096,
        "zMax": 4096,
        "centerX": 2048,
        "centerZ": 2048
      },
      {
        "id": "NE",
        "xMin": 4096,
        "zMin": 0,
        "xMax": 8192,
        "zMax": 4096,
        "centerX": 6144,
        "centerZ": 2048
      },
      {
        "id": "SW",
        "xMin": 0,
        "zMin": 4096,
        "xMax": 4096,
        "zMax": 8192,
        "centerX": 2048,
        "centerZ": 6144
      },
      {
        "id": "SE",
        "xMin": 4096,
        "zMin": 4096,
        "xMax": 8192,
        "zMax": 8192,
        "centerX": 6144,
        "centerZ": 6144
      }
    ]
  },
  {
    "coord": "B1",
    "name": "Orin Veil",
    "slug": "orin-veil-r1",
    "zone": "CORE",
    "security": "Patrolled Lanes (CORE)",
    "col": 1,
    "row": 0,
    "xMin": 8192,
    "zMin": 0,
    "xMax": 16384,
    "zMax": 8192,
    "sectors": [
      {
        "id": "NW",
        "xMin": 8192,
        "zMin": 0,
        "xMax": 12288,
        "zMax": 4096,
        "centerX": 10240,
        "centerZ": 2048
      },
      {
        "id": "NE",
        "xMin": 12288,
        "zMin": 0,
        "xMax": 16384,
        "zMax": 4096,
        "centerX": 14336,
        "centerZ": 2048
      },
      {
        "id": "SW",
        "xMin": 8192,
        "zMin": 4096,
        "xMax": 12288,
        "zMax": 8192,
        "centerX": 10240,
        "centerZ": 6144
      },
      {
        "id": "SE",
        "xMin": 12288,
        "zMin": 4096,
        "xMax": 16384,
        "zMax": 8192,
        "centerX": 14336,
        "centerZ": 6144
      }
    ]
  },
  {
    "coord": "C1",
    "name": "Helix Verge",
    "slug": "helix-verge-r2",
    "zone": "CORE",
    "security": "Patrolled Lanes (CORE)",
    "col": 2,
    "row": 0,
    "xMin": 16384,
    "zMin": 0,
    "xMax": 24576,
    "zMax": 8192,
    "sectors": [
      {
        "id": "NW",
        "xMin": 16384,
        "zMin": 0,
        "xMax": 20480,
        "zMax": 4096,
        "centerX": 18432,
        "centerZ": 2048
      },
      {
        "id": "NE",
        "xMin": 20480,
        "zMin": 0,
        "xMax": 24576,
        "zMax": 4096,
        "centerX": 22528,
        "centerZ": 2048
      },
      {
        "id": "SW",
        "xMin": 16384,
        "zMin": 4096,
        "xMax": 20480,
        "zMax": 8192,
        "centerX": 18432,
        "centerZ": 6144
      },
      {
        "id": "SE",
        "xMin": 20480,
        "zMin": 4096,
        "xMax": 24576,
        "zMax": 8192,
        "centerX": 22528,
        "centerZ": 6144
      }
    ]
  },
  {
    "coord": "D1",
    "name": "Carina Span",
    "slug": "carina-span-r3",
    "zone": "MID",
    "security": "Outer Lanes (MID)",
    "col": 3,
    "row": 0,
    "xMin": 24576,
    "zMin": 0,
    "xMax": 32768,
    "zMax": 8192,
    "sectors": [
      {
        "id": "NW",
        "xMin": 24576,
        "zMin": 0,
        "xMax": 28672,
        "zMax": 4096,
        "centerX": 26624,
        "centerZ": 2048
      },
      {
        "id": "NE",
        "xMin": 28672,
        "zMin": 0,
        "xMax": 32768,
        "zMax": 4096,
        "centerX": 30720,
        "centerZ": 2048
      },
      {
        "id": "SW",
        "xMin": 24576,
        "zMin": 4096,
        "xMax": 28672,
        "zMax": 8192,
        "centerX": 26624,
        "centerZ": 6144
      },
      {
        "id": "SE",
        "xMin": 28672,
        "zMin": 4096,
        "xMax": 32768,
        "zMax": 8192,
        "centerX": 30720,
        "centerZ": 6144
      }
    ]
  },
  {
    "coord": "E1",
    "name": "Drift Hollows",
    "slug": "drift-hollows-r4",
    "zone": "MID",
    "security": "Outer Lanes (MID)",
    "col": 4,
    "row": 0,
    "xMin": 32768,
    "zMin": 0,
    "xMax": 40960,
    "zMax": 8192,
    "sectors": [
      {
        "id": "NW",
        "xMin": 32768,
        "zMin": 0,
        "xMax": 36864,
        "zMax": 4096,
        "centerX": 34816,
        "centerZ": 2048
      },
      {
        "id": "NE",
        "xMin": 36864,
        "zMin": 0,
        "xMax": 40960,
        "zMax": 4096,
        "centerX": 38912,
        "centerZ": 2048
      },
      {
        "id": "SW",
        "xMin": 32768,
        "zMin": 4096,
        "xMax": 36864,
        "zMax": 8192,
        "centerX": 34816,
        "centerZ": 6144
      },
      {
        "id": "SE",
        "xMin": 36864,
        "zMin": 4096,
        "xMax": 40960,
        "zMax": 8192,
        "centerX": 38912,
        "centerZ": 6144
      }
    ]
  },
  {
    "coord": "F1",
    "name": "Korr Expanse",
    "slug": "korr-expanse-r5",
    "zone": "FRONTIER",
    "security": "Frontier (FRONTIER)",
    "col": 5,
    "row": 0,
    "xMin": 40960,
    "zMin": 0,
    "xMax": 49152,
    "zMax": 8192,
    "sectors": [
      {
        "id": "NW",
        "xMin": 40960,
        "zMin": 0,
        "xMax": 45056,
        "zMax": 4096,
        "centerX": 43008,
        "centerZ": 2048
      },
      {
        "id": "NE",
        "xMin": 45056,
        "zMin": 0,
        "xMax": 49152,
        "zMax": 4096,
        "centerX": 47104,
        "centerZ": 2048
      },
      {
        "id": "SW",
        "xMin": 40960,
        "zMin": 4096,
        "xMax": 45056,
        "zMax": 8192,
        "centerX": 43008,
        "centerZ": 6144
      },
      {
        "id": "SE",
        "xMin": 45056,
        "zMin": 4096,
        "xMax": 49152,
        "zMax": 8192,
        "centerX": 47104,
        "centerZ": 6144
      }
    ]
  },
  {
    "coord": "G1",
    "name": "Nyx Marches",
    "slug": "nyx-marches-r6",
    "zone": "MID",
    "security": "Outer Lanes (MID)",
    "col": 6,
    "row": 0,
    "xMin": 49152,
    "zMin": 0,
    "xMax": 57344,
    "zMax": 8192,
    "sectors": [
      {
        "id": "NW",
        "xMin": 49152,
        "zMin": 0,
        "xMax": 53248,
        "zMax": 4096,
        "centerX": 51200,
        "centerZ": 2048
      },
      {
        "id": "NE",
        "xMin": 53248,
        "zMin": 0,
        "xMax": 57344,
        "zMax": 4096,
        "centerX": 55296,
        "centerZ": 2048
      },
      {
        "id": "SW",
        "xMin": 49152,
        "zMin": 4096,
        "xMax": 53248,
        "zMax": 8192,
        "centerX": 51200,
        "centerZ": 6144
      },
      {
        "id": "SE",
        "xMin": 53248,
        "zMin": 4096,
        "xMax": 57344,
        "zMax": 8192,
        "centerX": 55296,
        "centerZ": 6144
      }
    ]
  },
  {
    "coord": "H1",
    "name": "Pyxis Quartz",
    "slug": "pyxis-quartz-r7",
    "zone": "FRONTIER",
    "security": "Frontier (FRONTIER)",
    "col": 7,
    "row": 0,
    "xMin": 57344,
    "zMin": 0,
    "xMax": 65536,
    "zMax": 8192,
    "sectors": [
      {
        "id": "NW",
        "xMin": 57344,
        "zMin": 0,
        "xMax": 61440,
        "zMax": 4096,
        "centerX": 59392,
        "centerZ": 2048
      },
      {
        "id": "NE",
        "xMin": 61440,
        "zMin": 0,
        "xMax": 65536,
        "zMax": 4096,
        "centerX": 63488,
        "centerZ": 2048
      },
      {
        "id": "SW",
        "xMin": 57344,
        "zMin": 4096,
        "xMax": 61440,
        "zMax": 8192,
        "centerX": 59392,
        "centerZ": 6144
      },
      {
        "id": "SE",
        "xMin": 61440,
        "zMin": 4096,
        "xMax": 65536,
        "zMax": 8192,
        "centerX": 63488,
        "centerZ": 6144
      }
    ]
  },
  {
    "coord": "A2",
    "name": "Solyn Cradle",
    "slug": "solyn-cradle-r8",
    "zone": "CORE",
    "security": "Patrolled Lanes (CORE)",
    "col": 0,
    "row": 1,
    "xMin": 0,
    "zMin": 8192,
    "xMax": 8192,
    "zMax": 16384,
    "sectors": [
      {
        "id": "NW",
        "xMin": 0,
        "zMin": 8192,
        "xMax": 4096,
        "zMax": 12288,
        "centerX": 2048,
        "centerZ": 10240
      },
      {
        "id": "NE",
        "xMin": 4096,
        "zMin": 8192,
        "xMax": 8192,
        "zMax": 12288,
        "centerX": 6144,
        "centerZ": 10240
      },
      {
        "id": "SW",
        "xMin": 0,
        "zMin": 12288,
        "xMax": 4096,
        "zMax": 16384,
        "centerX": 2048,
        "centerZ": 14336
      },
      {
        "id": "SE",
        "xMin": 4096,
        "zMin": 12288,
        "xMax": 8192,
        "zMax": 16384,
        "centerX": 6144,
        "centerZ": 14336
      }
    ]
  },
  {
    "coord": "B2",
    "name": "Tarsis Belt",
    "slug": "tarsis-belt-r9",
    "zone": "CORE",
    "security": "Patrolled Lanes (CORE)",
    "col": 1,
    "row": 1,
    "xMin": 8192,
    "zMin": 8192,
    "xMax": 16384,
    "zMax": 16384,
    "sectors": [
      {
        "id": "NW",
        "xMin": 8192,
        "zMin": 8192,
        "xMax": 12288,
        "zMax": 12288,
        "centerX": 10240,
        "centerZ": 10240
      },
      {
        "id": "NE",
        "xMin": 12288,
        "zMin": 8192,
        "xMax": 16384,
        "zMax": 12288,
        "centerX": 14336,
        "centerZ": 10240
      },
      {
        "id": "SW",
        "xMin": 8192,
        "zMin": 12288,
        "xMax": 12288,
        "zMax": 16384,
        "centerX": 10240,
        "centerZ": 14336
      },
      {
        "id": "SE",
        "xMin": 12288,
        "zMin": 12288,
        "xMax": 16384,
        "zMax": 16384,
        "centerX": 14336,
        "centerZ": 14336
      }
    ]
  },
  {
    "coord": "C2",
    "name": "Umbral Coil",
    "slug": "umbral-coil-r10",
    "zone": "MID",
    "security": "Outer Lanes (MID)",
    "col": 2,
    "row": 1,
    "xMin": 16384,
    "zMin": 8192,
    "xMax": 24576,
    "zMax": 16384,
    "sectors": [
      {
        "id": "NW",
        "xMin": 16384,
        "zMin": 8192,
        "xMax": 20480,
        "zMax": 12288,
        "centerX": 18432,
        "centerZ": 10240
      },
      {
        "id": "NE",
        "xMin": 20480,
        "zMin": 8192,
        "xMax": 24576,
        "zMax": 12288,
        "centerX": 22528,
        "centerZ": 10240
      },
      {
        "id": "SW",
        "xMin": 16384,
        "zMin": 12288,
        "xMax": 20480,
        "zMax": 16384,
        "centerX": 18432,
        "centerZ": 14336
      },
      {
        "id": "SE",
        "xMin": 20480,
        "zMin": 12288,
        "xMax": 24576,
        "zMax": 16384,
        "centerX": 22528,
        "centerZ": 14336
      }
    ]
  },
  {
    "coord": "D2",
    "name": "Wraith Hollow",
    "slug": "wraith-hollow-r11",
    "zone": "MID",
    "security": "Outer Lanes (MID)",
    "col": 3,
    "row": 1,
    "xMin": 24576,
    "zMin": 8192,
    "xMax": 32768,
    "zMax": 16384,
    "sectors": [
      {
        "id": "NW",
        "xMin": 24576,
        "zMin": 8192,
        "xMax": 28672,
        "zMax": 12288,
        "centerX": 26624,
        "centerZ": 10240
      },
      {
        "id": "NE",
        "xMin": 28672,
        "zMin": 8192,
        "xMax": 32768,
        "zMax": 12288,
        "centerX": 30720,
        "centerZ": 10240
      },
      {
        "id": "SW",
        "xMin": 24576,
        "zMin": 12288,
        "xMax": 28672,
        "zMax": 16384,
        "centerX": 26624,
        "centerZ": 14336
      },
      {
        "id": "SE",
        "xMin": 28672,
        "zMin": 12288,
        "xMax": 32768,
        "zMax": 16384,
        "centerX": 30720,
        "centerZ": 14336
      }
    ]
  },
  {
    "coord": "E2",
    "name": "Xanthe Drift",
    "slug": "xanthe-drift-r12",
    "zone": "MID",
    "security": "Outer Lanes (MID)",
    "col": 4,
    "row": 1,
    "xMin": 32768,
    "zMin": 8192,
    "xMax": 40960,
    "zMax": 16384,
    "sectors": [
      {
        "id": "NW",
        "xMin": 32768,
        "zMin": 8192,
        "xMax": 36864,
        "zMax": 12288,
        "centerX": 34816,
        "centerZ": 10240
      },
      {
        "id": "NE",
        "xMin": 36864,
        "zMin": 8192,
        "xMax": 40960,
        "zMax": 12288,
        "centerX": 38912,
        "centerZ": 10240
      },
      {
        "id": "SW",
        "xMin": 32768,
        "zMin": 12288,
        "xMax": 36864,
        "zMax": 16384,
        "centerX": 34816,
        "centerZ": 14336
      },
      {
        "id": "SE",
        "xMin": 36864,
        "zMin": 12288,
        "xMax": 40960,
        "zMax": 16384,
        "centerX": 38912,
        "centerZ": 14336
      }
    ]
  },
  {
    "coord": "F2",
    "name": "Yarrow Pale",
    "slug": "yarrow-pale-r13",
    "zone": "MID",
    "security": "Outer Lanes (MID)",
    "col": 5,
    "row": 1,
    "xMin": 40960,
    "zMin": 8192,
    "xMax": 49152,
    "zMax": 16384,
    "sectors": [
      {
        "id": "NW",
        "xMin": 40960,
        "zMin": 8192,
        "xMax": 45056,
        "zMax": 12288,
        "centerX": 43008,
        "centerZ": 10240
      },
      {
        "id": "NE",
        "xMin": 45056,
        "zMin": 8192,
        "xMax": 49152,
        "zMax": 12288,
        "centerX": 47104,
        "centerZ": 10240
      },
      {
        "id": "SW",
        "xMin": 40960,
        "zMin": 12288,
        "xMax": 45056,
        "zMax": 16384,
        "centerX": 43008,
        "centerZ": 14336
      },
      {
        "id": "SE",
        "xMin": 45056,
        "zMin": 12288,
        "xMax": 49152,
        "zMax": 16384,
        "centerX": 47104,
        "centerZ": 14336
      }
    ]
  },
  {
    "coord": "G2",
    "name": "Zephyr Crown",
    "slug": "zephyr-crown-r14",
    "zone": "FRONTIER",
    "security": "Frontier (FRONTIER)",
    "col": 6,
    "row": 1,
    "xMin": 49152,
    "zMin": 8192,
    "xMax": 57344,
    "zMax": 16384,
    "sectors": [
      {
        "id": "NW",
        "xMin": 49152,
        "zMin": 8192,
        "xMax": 53248,
        "zMax": 12288,
        "centerX": 51200,
        "centerZ": 10240
      },
      {
        "id": "NE",
        "xMin": 53248,
        "zMin": 8192,
        "xMax": 57344,
        "zMax": 12288,
        "centerX": 55296,
        "centerZ": 10240
      },
      {
        "id": "SW",
        "xMin": 49152,
        "zMin": 12288,
        "xMax": 53248,
        "zMax": 16384,
        "centerX": 51200,
        "centerZ": 14336
      },
      {
        "id": "SE",
        "xMin": 53248,
        "zMin": 12288,
        "xMax": 57344,
        "zMax": 16384,
        "centerX": 55296,
        "centerZ": 14336
      }
    ]
  },
  {
    "coord": "H2",
    "name": "Aeon Maw",
    "slug": "aeon-maw-r15",
    "zone": "FRONTIER",
    "security": "Frontier (FRONTIER)",
    "col": 7,
    "row": 1,
    "xMin": 57344,
    "zMin": 8192,
    "xMax": 65536,
    "zMax": 16384,
    "sectors": [
      {
        "id": "NW",
        "xMin": 57344,
        "zMin": 8192,
        "xMax": 61440,
        "zMax": 12288,
        "centerX": 59392,
        "centerZ": 10240
      },
      {
        "id": "NE",
        "xMin": 61440,
        "zMin": 8192,
        "xMax": 65536,
        "zMax": 12288,
        "centerX": 63488,
        "centerZ": 10240
      },
      {
        "id": "SW",
        "xMin": 57344,
        "zMin": 12288,
        "xMax": 61440,
        "zMax": 16384,
        "centerX": 59392,
        "centerZ": 14336
      },
      {
        "id": "SE",
        "xMin": 61440,
        "zMin": 12288,
        "xMax": 65536,
        "zMax": 16384,
        "centerX": 63488,
        "centerZ": 14336
      }
    ]
  },
  {
    "coord": "A3",
    "name": "Briar Cluster",
    "slug": "briar-cluster-r16",
    "zone": "CORE",
    "security": "Patrolled Lanes (CORE)",
    "col": 0,
    "row": 2,
    "xMin": 0,
    "zMin": 16384,
    "xMax": 8192,
    "zMax": 24576,
    "sectors": [
      {
        "id": "NW",
        "xMin": 0,
        "zMin": 16384,
        "xMax": 4096,
        "zMax": 20480,
        "centerX": 2048,
        "centerZ": 18432
      },
      {
        "id": "NE",
        "xMin": 4096,
        "zMin": 16384,
        "xMax": 8192,
        "zMax": 20480,
        "centerX": 6144,
        "centerZ": 18432
      },
      {
        "id": "SW",
        "xMin": 0,
        "zMin": 20480,
        "xMax": 4096,
        "zMax": 24576,
        "centerX": 2048,
        "centerZ": 22528
      },
      {
        "id": "SE",
        "xMin": 4096,
        "zMin": 20480,
        "xMax": 8192,
        "zMax": 24576,
        "centerX": 6144,
        "centerZ": 22528
      }
    ]
  },
  {
    "coord": "B3",
    "name": "Cassia Wash",
    "slug": "cassia-wash-r17",
    "zone": "MID",
    "security": "Outer Lanes (MID)",
    "col": 1,
    "row": 2,
    "xMin": 8192,
    "zMin": 16384,
    "xMax": 16384,
    "zMax": 24576,
    "sectors": [
      {
        "id": "NW",
        "xMin": 8192,
        "zMin": 16384,
        "xMax": 12288,
        "zMax": 20480,
        "centerX": 10240,
        "centerZ": 18432
      },
      {
        "id": "NE",
        "xMin": 12288,
        "zMin": 16384,
        "xMax": 16384,
        "zMax": 20480,
        "centerX": 14336,
        "centerZ": 18432
      },
      {
        "id": "SW",
        "xMin": 8192,
        "zMin": 20480,
        "xMax": 12288,
        "zMax": 24576,
        "centerX": 10240,
        "centerZ": 22528
      },
      {
        "id": "SE",
        "xMin": 12288,
        "zMin": 20480,
        "xMax": 16384,
        "zMax": 24576,
        "centerX": 14336,
        "centerZ": 22528
      }
    ]
  },
  {
    "coord": "C3",
    "name": "Dross Field",
    "slug": "dross-field-r18",
    "zone": "MID",
    "security": "Outer Lanes (MID)",
    "col": 2,
    "row": 2,
    "xMin": 16384,
    "zMin": 16384,
    "xMax": 24576,
    "zMax": 24576,
    "sectors": [
      {
        "id": "NW",
        "xMin": 16384,
        "zMin": 16384,
        "xMax": 20480,
        "zMax": 20480,
        "centerX": 18432,
        "centerZ": 18432
      },
      {
        "id": "NE",
        "xMin": 20480,
        "zMin": 16384,
        "xMax": 24576,
        "zMax": 20480,
        "centerX": 22528,
        "centerZ": 18432
      },
      {
        "id": "SW",
        "xMin": 16384,
        "zMin": 20480,
        "xMax": 20480,
        "zMax": 24576,
        "centerX": 18432,
        "centerZ": 22528
      },
      {
        "id": "SE",
        "xMin": 20480,
        "zMin": 20480,
        "xMax": 24576,
        "zMax": 24576,
        "centerX": 22528,
        "centerZ": 22528
      }
    ]
  },
  {
    "coord": "D3",
    "name": "Echo Trace",
    "slug": "echo-trace-r19",
    "zone": "FRONTIER",
    "security": "Frontier (FRONTIER)",
    "col": 3,
    "row": 2,
    "xMin": 24576,
    "zMin": 16384,
    "xMax": 32768,
    "zMax": 24576,
    "sectors": [
      {
        "id": "NW",
        "xMin": 24576,
        "zMin": 16384,
        "xMax": 28672,
        "zMax": 20480,
        "centerX": 26624,
        "centerZ": 18432
      },
      {
        "id": "NE",
        "xMin": 28672,
        "zMin": 16384,
        "xMax": 32768,
        "zMax": 20480,
        "centerX": 30720,
        "centerZ": 18432
      },
      {
        "id": "SW",
        "xMin": 24576,
        "zMin": 20480,
        "xMax": 28672,
        "zMax": 24576,
        "centerX": 26624,
        "centerZ": 22528
      },
      {
        "id": "SE",
        "xMin": 28672,
        "zMin": 20480,
        "xMax": 32768,
        "zMax": 24576,
        "centerX": 30720,
        "centerZ": 22528
      }
    ]
  },
  {
    "coord": "E3",
    "name": "Fenix Shadow",
    "slug": "fenix-shadow-r20",
    "zone": "MID",
    "security": "Outer Lanes (MID)",
    "col": 4,
    "row": 2,
    "xMin": 32768,
    "zMin": 16384,
    "xMax": 40960,
    "zMax": 24576,
    "sectors": [
      {
        "id": "NW",
        "xMin": 32768,
        "zMin": 16384,
        "xMax": 36864,
        "zMax": 20480,
        "centerX": 34816,
        "centerZ": 18432
      },
      {
        "id": "NE",
        "xMin": 36864,
        "zMin": 16384,
        "xMax": 40960,
        "zMax": 20480,
        "centerX": 38912,
        "centerZ": 18432
      },
      {
        "id": "SW",
        "xMin": 32768,
        "zMin": 20480,
        "xMax": 36864,
        "zMax": 24576,
        "centerX": 34816,
        "centerZ": 22528
      },
      {
        "id": "SE",
        "xMin": 36864,
        "zMin": 20480,
        "xMax": 40960,
        "zMax": 24576,
        "centerX": 38912,
        "centerZ": 22528
      }
    ]
  },
  {
    "coord": "F3",
    "name": "Galen Mouth",
    "slug": "galen-mouth-r21",
    "zone": "FRONTIER",
    "security": "Frontier (FRONTIER)",
    "col": 5,
    "row": 2,
    "xMin": 40960,
    "zMin": 16384,
    "xMax": 49152,
    "zMax": 24576,
    "sectors": [
      {
        "id": "NW",
        "xMin": 40960,
        "zMin": 16384,
        "xMax": 45056,
        "zMax": 20480,
        "centerX": 43008,
        "centerZ": 18432
      },
      {
        "id": "NE",
        "xMin": 45056,
        "zMin": 16384,
        "xMax": 49152,
        "zMax": 20480,
        "centerX": 47104,
        "centerZ": 18432
      },
      {
        "id": "SW",
        "xMin": 40960,
        "zMin": 20480,
        "xMax": 45056,
        "zMax": 24576,
        "centerX": 43008,
        "centerZ": 22528
      },
      {
        "id": "SE",
        "xMin": 45056,
        "zMin": 20480,
        "xMax": 49152,
        "zMax": 24576,
        "centerX": 47104,
        "centerZ": 22528
      }
    ]
  },
  {
    "coord": "G3",
    "name": "Hesper Edge",
    "slug": "hesper-edge-r22",
    "zone": "FRONTIER",
    "security": "Frontier (FRONTIER)",
    "col": 6,
    "row": 2,
    "xMin": 49152,
    "zMin": 16384,
    "xMax": 57344,
    "zMax": 24576,
    "sectors": [
      {
        "id": "NW",
        "xMin": 49152,
        "zMin": 16384,
        "xMax": 53248,
        "zMax": 20480,
        "centerX": 51200,
        "centerZ": 18432
      },
      {
        "id": "NE",
        "xMin": 53248,
        "zMin": 16384,
        "xMax": 57344,
        "zMax": 20480,
        "centerX": 55296,
        "centerZ": 18432
      },
      {
        "id": "SW",
        "xMin": 49152,
        "zMin": 20480,
        "xMax": 53248,
        "zMax": 24576,
        "centerX": 51200,
        "centerZ": 22528
      },
      {
        "id": "SE",
        "xMin": 53248,
        "zMin": 20480,
        "xMax": 57344,
        "zMax": 24576,
        "centerX": 55296,
        "centerZ": 22528
      }
    ]
  },
  {
    "coord": "H3",
    "name": "Indigo Throne",
    "slug": "indigo-throne-r23",
    "zone": "FRONTIER",
    "security": "Frontier (FRONTIER)",
    "col": 7,
    "row": 2,
    "xMin": 57344,
    "zMin": 16384,
    "xMax": 65536,
    "zMax": 24576,
    "sectors": [
      {
        "id": "NW",
        "xMin": 57344,
        "zMin": 16384,
        "xMax": 61440,
        "zMax": 20480,
        "centerX": 59392,
        "centerZ": 18432
      },
      {
        "id": "NE",
        "xMin": 61440,
        "zMin": 16384,
        "xMax": 65536,
        "zMax": 20480,
        "centerX": 63488,
        "centerZ": 18432
      },
      {
        "id": "SW",
        "xMin": 57344,
        "zMin": 20480,
        "xMax": 61440,
        "zMax": 24576,
        "centerX": 59392,
        "centerZ": 22528
      },
      {
        "id": "SE",
        "xMin": 61440,
        "zMin": 20480,
        "xMax": 65536,
        "zMax": 24576,
        "centerX": 63488,
        "centerZ": 22528
      }
    ]
  },
  {
    "coord": "A4",
    "name": "Janus Spire",
    "slug": "janus-spire-r24",
    "zone": "MID",
    "security": "Outer Lanes (MID)",
    "col": 0,
    "row": 3,
    "xMin": 0,
    "zMin": 24576,
    "xMax": 8192,
    "zMax": 32768,
    "sectors": [
      {
        "id": "NW",
        "xMin": 0,
        "zMin": 24576,
        "xMax": 4096,
        "zMax": 28672,
        "centerX": 2048,
        "centerZ": 26624
      },
      {
        "id": "NE",
        "xMin": 4096,
        "zMin": 24576,
        "xMax": 8192,
        "zMax": 28672,
        "centerX": 6144,
        "centerZ": 26624
      },
      {
        "id": "SW",
        "xMin": 0,
        "zMin": 28672,
        "xMax": 4096,
        "zMax": 32768,
        "centerX": 2048,
        "centerZ": 30720
      },
      {
        "id": "SE",
        "xMin": 4096,
        "zMin": 28672,
        "xMax": 8192,
        "zMax": 32768,
        "centerX": 6144,
        "centerZ": 30720
      }
    ]
  },
  {
    "coord": "B4",
    "name": "Kestrel Gulf",
    "slug": "kestrel-gulf-r25",
    "zone": "MID",
    "security": "Outer Lanes (MID)",
    "col": 1,
    "row": 3,
    "xMin": 8192,
    "zMin": 24576,
    "xMax": 16384,
    "zMax": 32768,
    "sectors": [
      {
        "id": "NW",
        "xMin": 8192,
        "zMin": 24576,
        "xMax": 12288,
        "zMax": 28672,
        "centerX": 10240,
        "centerZ": 26624
      },
      {
        "id": "NE",
        "xMin": 12288,
        "zMin": 24576,
        "xMax": 16384,
        "zMax": 28672,
        "centerX": 14336,
        "centerZ": 26624
      },
      {
        "id": "SW",
        "xMin": 8192,
        "zMin": 28672,
        "xMax": 12288,
        "zMax": 32768,
        "centerX": 10240,
        "centerZ": 30720
      },
      {
        "id": "SE",
        "xMin": 12288,
        "zMin": 28672,
        "xMax": 16384,
        "zMax": 32768,
        "centerX": 14336,
        "centerZ": 30720
      }
    ]
  },
  {
    "coord": "C4",
    "name": "Lyra Glade",
    "slug": "lyra-glade-r26",
    "zone": "MID",
    "security": "Outer Lanes (MID)",
    "col": 2,
    "row": 3,
    "xMin": 16384,
    "zMin": 24576,
    "xMax": 24576,
    "zMax": 32768,
    "sectors": [
      {
        "id": "NW",
        "xMin": 16384,
        "zMin": 24576,
        "xMax": 20480,
        "zMax": 28672,
        "centerX": 18432,
        "centerZ": 26624
      },
      {
        "id": "NE",
        "xMin": 20480,
        "zMin": 24576,
        "xMax": 24576,
        "zMax": 28672,
        "centerX": 22528,
        "centerZ": 26624
      },
      {
        "id": "SW",
        "xMin": 16384,
        "zMin": 28672,
        "xMax": 20480,
        "zMax": 32768,
        "centerX": 18432,
        "centerZ": 30720
      },
      {
        "id": "SE",
        "xMin": 20480,
        "zMin": 28672,
        "xMax": 24576,
        "zMax": 32768,
        "centerX": 22528,
        "centerZ": 30720
      }
    ]
  },
  {
    "coord": "D4",
    "name": "Mira Knot",
    "slug": "mira-knot-r27",
    "zone": "MID",
    "security": "Outer Lanes (MID)",
    "col": 3,
    "row": 3,
    "xMin": 24576,
    "zMin": 24576,
    "xMax": 32768,
    "zMax": 32768,
    "sectors": [
      {
        "id": "NW",
        "xMin": 24576,
        "zMin": 24576,
        "xMax": 28672,
        "zMax": 28672,
        "centerX": 26624,
        "centerZ": 26624
      },
      {
        "id": "NE",
        "xMin": 28672,
        "zMin": 24576,
        "xMax": 32768,
        "zMax": 28672,
        "centerX": 30720,
        "centerZ": 26624
      },
      {
        "id": "SW",
        "xMin": 24576,
        "zMin": 28672,
        "xMax": 28672,
        "zMax": 32768,
        "centerX": 26624,
        "centerZ": 30720
      },
      {
        "id": "SE",
        "xMin": 28672,
        "zMin": 28672,
        "xMax": 32768,
        "zMax": 32768,
        "centerX": 30720,
        "centerZ": 30720
      }
    ]
  },
  {
    "coord": "E4",
    "name": "Nimbus Shoals",
    "slug": "nimbus-shoals-r28",
    "zone": "FRONTIER",
    "security": "Frontier (FRONTIER)",
    "col": 4,
    "row": 3,
    "xMin": 32768,
    "zMin": 24576,
    "xMax": 40960,
    "zMax": 32768,
    "sectors": [
      {
        "id": "NW",
        "xMin": 32768,
        "zMin": 24576,
        "xMax": 36864,
        "zMax": 28672,
        "centerX": 34816,
        "centerZ": 26624
      },
      {
        "id": "NE",
        "xMin": 36864,
        "zMin": 24576,
        "xMax": 40960,
        "zMax": 28672,
        "centerX": 38912,
        "centerZ": 26624
      },
      {
        "id": "SW",
        "xMin": 32768,
        "zMin": 28672,
        "xMax": 36864,
        "zMax": 32768,
        "centerX": 34816,
        "centerZ": 30720
      },
      {
        "id": "SE",
        "xMin": 36864,
        "zMin": 28672,
        "xMax": 40960,
        "zMax": 32768,
        "centerX": 38912,
        "centerZ": 30720
      }
    ]
  },
  {
    "coord": "F4",
    "name": "Orpheus Tide",
    "slug": "orpheus-tide-r29",
    "zone": "FRONTIER",
    "security": "Frontier (FRONTIER)",
    "col": 5,
    "row": 3,
    "xMin": 40960,
    "zMin": 24576,
    "xMax": 49152,
    "zMax": 32768,
    "sectors": [
      {
        "id": "NW",
        "xMin": 40960,
        "zMin": 24576,
        "xMax": 45056,
        "zMax": 28672,
        "centerX": 43008,
        "centerZ": 26624
      },
      {
        "id": "NE",
        "xMin": 45056,
        "zMin": 24576,
        "xMax": 49152,
        "zMax": 28672,
        "centerX": 47104,
        "centerZ": 26624
      },
      {
        "id": "SW",
        "xMin": 40960,
        "zMin": 28672,
        "xMax": 45056,
        "zMax": 32768,
        "centerX": 43008,
        "centerZ": 30720
      },
      {
        "id": "SE",
        "xMin": 45056,
        "zMin": 28672,
        "xMax": 49152,
        "zMax": 32768,
        "centerX": 47104,
        "centerZ": 30720
      }
    ]
  },
  {
    "coord": "G4",
    "name": "Pyre Sweep",
    "slug": "pyre-sweep-r30",
    "zone": "NULL",
    "security": "Wild Drift (NULL)",
    "col": 6,
    "row": 3,
    "xMin": 49152,
    "zMin": 24576,
    "xMax": 57344,
    "zMax": 32768,
    "sectors": [
      {
        "id": "NW",
        "xMin": 49152,
        "zMin": 24576,
        "xMax": 53248,
        "zMax": 28672,
        "centerX": 51200,
        "centerZ": 26624
      },
      {
        "id": "NE",
        "xMin": 53248,
        "zMin": 24576,
        "xMax": 57344,
        "zMax": 28672,
        "centerX": 55296,
        "centerZ": 26624
      },
      {
        "id": "SW",
        "xMin": 49152,
        "zMin": 28672,
        "xMax": 53248,
        "zMax": 32768,
        "centerX": 51200,
        "centerZ": 30720
      },
      {
        "id": "SE",
        "xMin": 53248,
        "zMin": 28672,
        "xMax": 57344,
        "zMax": 32768,
        "centerX": 55296,
        "centerZ": 30720
      }
    ]
  },
  {
    "coord": "H4",
    "name": "Quill Marsh",
    "slug": "quill-marsh-r31",
    "zone": "FRONTIER",
    "security": "Frontier (FRONTIER)",
    "col": 7,
    "row": 3,
    "xMin": 57344,
    "zMin": 24576,
    "xMax": 65536,
    "zMax": 32768,
    "sectors": [
      {
        "id": "NW",
        "xMin": 57344,
        "zMin": 24576,
        "xMax": 61440,
        "zMax": 28672,
        "centerX": 59392,
        "centerZ": 26624
      },
      {
        "id": "NE",
        "xMin": 61440,
        "zMin": 24576,
        "xMax": 65536,
        "zMax": 28672,
        "centerX": 63488,
        "centerZ": 26624
      },
      {
        "id": "SW",
        "xMin": 57344,
        "zMin": 28672,
        "xMax": 61440,
        "zMax": 32768,
        "centerX": 59392,
        "centerZ": 30720
      },
      {
        "id": "SE",
        "xMin": 61440,
        "zMin": 28672,
        "xMax": 65536,
        "zMax": 32768,
        "centerX": 63488,
        "centerZ": 30720
      }
    ]
  },
  {
    "coord": "A5",
    "name": "Sable Fold",
    "slug": "sable-fold-r32",
    "zone": "MID",
    "security": "Outer Lanes (MID)",
    "col": 0,
    "row": 4,
    "xMin": 0,
    "zMin": 32768,
    "xMax": 8192,
    "zMax": 40960,
    "sectors": [
      {
        "id": "NW",
        "xMin": 0,
        "zMin": 32768,
        "xMax": 4096,
        "zMax": 36864,
        "centerX": 2048,
        "centerZ": 34816
      },
      {
        "id": "NE",
        "xMin": 4096,
        "zMin": 32768,
        "xMax": 8192,
        "zMax": 36864,
        "centerX": 6144,
        "centerZ": 34816
      },
      {
        "id": "SW",
        "xMin": 0,
        "zMin": 36864,
        "xMax": 4096,
        "zMax": 40960,
        "centerX": 2048,
        "centerZ": 38912
      },
      {
        "id": "SE",
        "xMin": 4096,
        "zMin": 36864,
        "xMax": 8192,
        "zMax": 40960,
        "centerX": 6144,
        "centerZ": 38912
      }
    ]
  },
  {
    "coord": "B5",
    "name": "Theron Bound",
    "slug": "theron-bound-r33",
    "zone": "MID",
    "security": "Outer Lanes (MID)",
    "col": 1,
    "row": 4,
    "xMin": 8192,
    "zMin": 32768,
    "xMax": 16384,
    "zMax": 40960,
    "sectors": [
      {
        "id": "NW",
        "xMin": 8192,
        "zMin": 32768,
        "xMax": 12288,
        "zMax": 36864,
        "centerX": 10240,
        "centerZ": 34816
      },
      {
        "id": "NE",
        "xMin": 12288,
        "zMin": 32768,
        "xMax": 16384,
        "zMax": 36864,
        "centerX": 14336,
        "centerZ": 34816
      },
      {
        "id": "SW",
        "xMin": 8192,
        "zMin": 36864,
        "xMax": 12288,
        "zMax": 40960,
        "centerX": 10240,
        "centerZ": 38912
      },
      {
        "id": "SE",
        "xMin": 12288,
        "zMin": 36864,
        "xMax": 16384,
        "zMax": 40960,
        "centerX": 14336,
        "centerZ": 38912
      }
    ]
  },
  {
    "coord": "C5",
    "name": "Ursa Crest",
    "slug": "ursa-crest-r34",
    "zone": "MID",
    "security": "Outer Lanes (MID)",
    "col": 2,
    "row": 4,
    "xMin": 16384,
    "zMin": 32768,
    "xMax": 24576,
    "zMax": 40960,
    "sectors": [
      {
        "id": "NW",
        "xMin": 16384,
        "zMin": 32768,
        "xMax": 20480,
        "zMax": 36864,
        "centerX": 18432,
        "centerZ": 34816
      },
      {
        "id": "NE",
        "xMin": 20480,
        "zMin": 32768,
        "xMax": 24576,
        "zMax": 36864,
        "centerX": 22528,
        "centerZ": 34816
      },
      {
        "id": "SW",
        "xMin": 16384,
        "zMin": 36864,
        "xMax": 20480,
        "zMax": 40960,
        "centerX": 18432,
        "centerZ": 38912
      },
      {
        "id": "SE",
        "xMin": 20480,
        "zMin": 36864,
        "xMax": 24576,
        "zMax": 40960,
        "centerX": 22528,
        "centerZ": 38912
      }
    ]
  },
  {
    "coord": "D5",
    "name": "Vesper Hollow",
    "slug": "vesper-hollow-r35",
    "zone": "FRONTIER",
    "security": "Frontier (FRONTIER)",
    "col": 3,
    "row": 4,
    "xMin": 24576,
    "zMin": 32768,
    "xMax": 32768,
    "zMax": 40960,
    "sectors": [
      {
        "id": "NW",
        "xMin": 24576,
        "zMin": 32768,
        "xMax": 28672,
        "zMax": 36864,
        "centerX": 26624,
        "centerZ": 34816
      },
      {
        "id": "NE",
        "xMin": 28672,
        "zMin": 32768,
        "xMax": 32768,
        "zMax": 36864,
        "centerX": 30720,
        "centerZ": 34816
      },
      {
        "id": "SW",
        "xMin": 24576,
        "zMin": 36864,
        "xMax": 28672,
        "zMax": 40960,
        "centerX": 26624,
        "centerZ": 38912
      },
      {
        "id": "SE",
        "xMin": 28672,
        "zMin": 36864,
        "xMax": 32768,
        "zMax": 40960,
        "centerX": 30720,
        "centerZ": 38912
      }
    ]
  },
  {
    "coord": "E5",
    "name": "Wraith Span",
    "slug": "wraith-span-r36",
    "zone": "FRONTIER",
    "security": "Frontier (FRONTIER)",
    "col": 4,
    "row": 4,
    "xMin": 32768,
    "zMin": 32768,
    "xMax": 40960,
    "zMax": 40960,
    "sectors": [
      {
        "id": "NW",
        "xMin": 32768,
        "zMin": 32768,
        "xMax": 36864,
        "zMax": 36864,
        "centerX": 34816,
        "centerZ": 34816
      },
      {
        "id": "NE",
        "xMin": 36864,
        "zMin": 32768,
        "xMax": 40960,
        "zMax": 36864,
        "centerX": 38912,
        "centerZ": 34816
      },
      {
        "id": "SW",
        "xMin": 32768,
        "zMin": 36864,
        "xMax": 36864,
        "zMax": 40960,
        "centerX": 34816,
        "centerZ": 38912
      },
      {
        "id": "SE",
        "xMin": 36864,
        "zMin": 36864,
        "xMax": 40960,
        "zMax": 40960,
        "centerX": 38912,
        "centerZ": 38912
      }
    ]
  },
  {
    "coord": "F5",
    "name": "Xeric Reach",
    "slug": "xeric-reach-r37",
    "zone": "FRONTIER",
    "security": "Frontier (FRONTIER)",
    "col": 5,
    "row": 4,
    "xMin": 40960,
    "zMin": 32768,
    "xMax": 49152,
    "zMax": 40960,
    "sectors": [
      {
        "id": "NW",
        "xMin": 40960,
        "zMin": 32768,
        "xMax": 45056,
        "zMax": 36864,
        "centerX": 43008,
        "centerZ": 34816
      },
      {
        "id": "NE",
        "xMin": 45056,
        "zMin": 32768,
        "xMax": 49152,
        "zMax": 36864,
        "centerX": 47104,
        "centerZ": 34816
      },
      {
        "id": "SW",
        "xMin": 40960,
        "zMin": 36864,
        "xMax": 45056,
        "zMax": 40960,
        "centerX": 43008,
        "centerZ": 38912
      },
      {
        "id": "SE",
        "xMin": 45056,
        "zMin": 36864,
        "xMax": 49152,
        "zMax": 40960,
        "centerX": 47104,
        "centerZ": 38912
      }
    ]
  },
  {
    "coord": "G5",
    "name": "Yotun Drift",
    "slug": "yotun-drift-r38",
    "zone": "FRONTIER",
    "security": "Frontier (FRONTIER)",
    "col": 6,
    "row": 4,
    "xMin": 49152,
    "zMin": 32768,
    "xMax": 57344,
    "zMax": 40960,
    "sectors": [
      {
        "id": "NW",
        "xMin": 49152,
        "zMin": 32768,
        "xMax": 53248,
        "zMax": 36864,
        "centerX": 51200,
        "centerZ": 34816
      },
      {
        "id": "NE",
        "xMin": 53248,
        "zMin": 32768,
        "xMax": 57344,
        "zMax": 36864,
        "centerX": 55296,
        "centerZ": 34816
      },
      {
        "id": "SW",
        "xMin": 49152,
        "zMin": 36864,
        "xMax": 53248,
        "zMax": 40960,
        "centerX": 51200,
        "centerZ": 38912
      },
      {
        "id": "SE",
        "xMin": 53248,
        "zMin": 36864,
        "xMax": 57344,
        "zMax": 40960,
        "centerX": 55296,
        "centerZ": 38912
      }
    ]
  },
  {
    "coord": "H5",
    "name": "Zorya Veil",
    "slug": "zorya-veil-r39",
    "zone": "FRONTIER",
    "security": "Frontier (FRONTIER)",
    "col": 7,
    "row": 4,
    "xMin": 57344,
    "zMin": 32768,
    "xMax": 65536,
    "zMax": 40960,
    "sectors": [
      {
        "id": "NW",
        "xMin": 57344,
        "zMin": 32768,
        "xMax": 61440,
        "zMax": 36864,
        "centerX": 59392,
        "centerZ": 34816
      },
      {
        "id": "NE",
        "xMin": 61440,
        "zMin": 32768,
        "xMax": 65536,
        "zMax": 36864,
        "centerX": 63488,
        "centerZ": 34816
      },
      {
        "id": "SW",
        "xMin": 57344,
        "zMin": 36864,
        "xMax": 61440,
        "zMax": 40960,
        "centerX": 59392,
        "centerZ": 38912
      },
      {
        "id": "SE",
        "xMin": 61440,
        "zMin": 36864,
        "xMax": 65536,
        "zMax": 40960,
        "centerX": 63488,
        "centerZ": 38912
      }
    ]
  },
  {
    "coord": "A6",
    "name": "Astor Cinder",
    "slug": "astor-cinder-r40",
    "zone": "CORE",
    "security": "Patrolled Lanes (CORE)",
    "col": 0,
    "row": 5,
    "xMin": 0,
    "zMin": 40960,
    "xMax": 8192,
    "zMax": 49152,
    "sectors": [
      {
        "id": "NW",
        "xMin": 0,
        "zMin": 40960,
        "xMax": 4096,
        "zMax": 45056,
        "centerX": 2048,
        "centerZ": 43008
      },
      {
        "id": "NE",
        "xMin": 4096,
        "zMin": 40960,
        "xMax": 8192,
        "zMax": 45056,
        "centerX": 6144,
        "centerZ": 43008
      },
      {
        "id": "SW",
        "xMin": 0,
        "zMin": 45056,
        "xMax": 4096,
        "zMax": 49152,
        "centerX": 2048,
        "centerZ": 47104
      },
      {
        "id": "SE",
        "xMin": 4096,
        "zMin": 45056,
        "xMax": 8192,
        "zMax": 49152,
        "centerX": 6144,
        "centerZ": 47104
      }
    ]
  },
  {
    "coord": "B6",
    "name": "Brae Threshold",
    "slug": "brae-threshold-r41",
    "zone": "FRONTIER",
    "security": "Frontier (FRONTIER)",
    "col": 1,
    "row": 5,
    "xMin": 8192,
    "zMin": 40960,
    "xMax": 16384,
    "zMax": 49152,
    "sectors": [
      {
        "id": "NW",
        "xMin": 8192,
        "zMin": 40960,
        "xMax": 12288,
        "zMax": 45056,
        "centerX": 10240,
        "centerZ": 43008
      },
      {
        "id": "NE",
        "xMin": 12288,
        "zMin": 40960,
        "xMax": 16384,
        "zMax": 45056,
        "centerX": 14336,
        "centerZ": 43008
      },
      {
        "id": "SW",
        "xMin": 8192,
        "zMin": 45056,
        "xMax": 12288,
        "zMax": 49152,
        "centerX": 10240,
        "centerZ": 47104
      },
      {
        "id": "SE",
        "xMin": 12288,
        "zMin": 45056,
        "xMax": 16384,
        "zMax": 49152,
        "centerX": 14336,
        "centerZ": 47104
      }
    ]
  },
  {
    "coord": "C6",
    "name": "Calix Cradle",
    "slug": "calix-cradle-r42",
    "zone": "MID",
    "security": "Outer Lanes (MID)",
    "col": 2,
    "row": 5,
    "xMin": 16384,
    "zMin": 40960,
    "xMax": 24576,
    "zMax": 49152,
    "sectors": [
      {
        "id": "NW",
        "xMin": 16384,
        "zMin": 40960,
        "xMax": 20480,
        "zMax": 45056,
        "centerX": 18432,
        "centerZ": 43008
      },
      {
        "id": "NE",
        "xMin": 20480,
        "zMin": 40960,
        "xMax": 24576,
        "zMax": 45056,
        "centerX": 22528,
        "centerZ": 43008
      },
      {
        "id": "SW",
        "xMin": 16384,
        "zMin": 45056,
        "xMax": 20480,
        "zMax": 49152,
        "centerX": 18432,
        "centerZ": 47104
      },
      {
        "id": "SE",
        "xMin": 20480,
        "zMin": 45056,
        "xMax": 24576,
        "zMax": 49152,
        "centerX": 22528,
        "centerZ": 47104
      }
    ]
  },
  {
    "coord": "D6",
    "name": "Dvalin Steep",
    "slug": "dvalin-steep-r43",
    "zone": "FRONTIER",
    "security": "Frontier (FRONTIER)",
    "col": 3,
    "row": 5,
    "xMin": 24576,
    "zMin": 40960,
    "xMax": 32768,
    "zMax": 49152,
    "sectors": [
      {
        "id": "NW",
        "xMin": 24576,
        "zMin": 40960,
        "xMax": 28672,
        "zMax": 45056,
        "centerX": 26624,
        "centerZ": 43008
      },
      {
        "id": "NE",
        "xMin": 28672,
        "zMin": 40960,
        "xMax": 32768,
        "zMax": 45056,
        "centerX": 30720,
        "centerZ": 43008
      },
      {
        "id": "SW",
        "xMin": 24576,
        "zMin": 45056,
        "xMax": 28672,
        "zMax": 49152,
        "centerX": 26624,
        "centerZ": 47104
      },
      {
        "id": "SE",
        "xMin": 28672,
        "zMin": 45056,
        "xMax": 32768,
        "zMax": 49152,
        "centerX": 30720,
        "centerZ": 47104
      }
    ]
  },
  {
    "coord": "E6",
    "name": "Erebos Hollow",
    "slug": "erebos-hollow-r44",
    "zone": "FRONTIER",
    "security": "Frontier (FRONTIER)",
    "col": 4,
    "row": 5,
    "xMin": 32768,
    "zMin": 40960,
    "xMax": 40960,
    "zMax": 49152,
    "sectors": [
      {
        "id": "NW",
        "xMin": 32768,
        "zMin": 40960,
        "xMax": 36864,
        "zMax": 45056,
        "centerX": 34816,
        "centerZ": 43008
      },
      {
        "id": "NE",
        "xMin": 36864,
        "zMin": 40960,
        "xMax": 40960,
        "zMax": 45056,
        "centerX": 38912,
        "centerZ": 43008
      },
      {
        "id": "SW",
        "xMin": 32768,
        "zMin": 45056,
        "xMax": 36864,
        "zMax": 49152,
        "centerX": 34816,
        "centerZ": 47104
      },
      {
        "id": "SE",
        "xMin": 36864,
        "zMin": 45056,
        "xMax": 40960,
        "zMax": 49152,
        "centerX": 38912,
        "centerZ": 47104
      }
    ]
  },
  {
    "coord": "F6",
    "name": "Fjord Verge",
    "slug": "fjord-verge-r45",
    "zone": "FRONTIER",
    "security": "Frontier (FRONTIER)",
    "col": 5,
    "row": 5,
    "xMin": 40960,
    "zMin": 40960,
    "xMax": 49152,
    "zMax": 49152,
    "sectors": [
      {
        "id": "NW",
        "xMin": 40960,
        "zMin": 40960,
        "xMax": 45056,
        "zMax": 45056,
        "centerX": 43008,
        "centerZ": 43008
      },
      {
        "id": "NE",
        "xMin": 45056,
        "zMin": 40960,
        "xMax": 49152,
        "zMax": 45056,
        "centerX": 47104,
        "centerZ": 43008
      },
      {
        "id": "SW",
        "xMin": 40960,
        "zMin": 45056,
        "xMax": 45056,
        "zMax": 49152,
        "centerX": 43008,
        "centerZ": 47104
      },
      {
        "id": "SE",
        "xMin": 45056,
        "zMin": 45056,
        "xMax": 49152,
        "zMax": 49152,
        "centerX": 47104,
        "centerZ": 47104
      }
    ]
  },
  {
    "coord": "G6",
    "name": "Garm Span",
    "slug": "garm-span-r46",
    "zone": "FRONTIER",
    "security": "Frontier (FRONTIER)",
    "col": 6,
    "row": 5,
    "xMin": 49152,
    "zMin": 40960,
    "xMax": 57344,
    "zMax": 49152,
    "sectors": [
      {
        "id": "NW",
        "xMin": 49152,
        "zMin": 40960,
        "xMax": 53248,
        "zMax": 45056,
        "centerX": 51200,
        "centerZ": 43008
      },
      {
        "id": "NE",
        "xMin": 53248,
        "zMin": 40960,
        "xMax": 57344,
        "zMax": 45056,
        "centerX": 55296,
        "centerZ": 43008
      },
      {
        "id": "SW",
        "xMin": 49152,
        "zMin": 45056,
        "xMax": 53248,
        "zMax": 49152,
        "centerX": 51200,
        "centerZ": 47104
      },
      {
        "id": "SE",
        "xMin": 53248,
        "zMin": 45056,
        "xMax": 57344,
        "zMax": 49152,
        "centerX": 55296,
        "centerZ": 47104
      }
    ]
  },
  {
    "coord": "H6",
    "name": "Hyacinth Maw",
    "slug": "hyacinth-maw-r47",
    "zone": "NULL",
    "security": "Wild Drift (NULL)",
    "col": 7,
    "row": 5,
    "xMin": 57344,
    "zMin": 40960,
    "xMax": 65536,
    "zMax": 49152,
    "sectors": [
      {
        "id": "NW",
        "xMin": 57344,
        "zMin": 40960,
        "xMax": 61440,
        "zMax": 45056,
        "centerX": 59392,
        "centerZ": 43008
      },
      {
        "id": "NE",
        "xMin": 61440,
        "zMin": 40960,
        "xMax": 65536,
        "zMax": 45056,
        "centerX": 63488,
        "centerZ": 43008
      },
      {
        "id": "SW",
        "xMin": 57344,
        "zMin": 45056,
        "xMax": 61440,
        "zMax": 49152,
        "centerX": 59392,
        "centerZ": 47104
      },
      {
        "id": "SE",
        "xMin": 61440,
        "zMin": 45056,
        "xMax": 65536,
        "zMax": 49152,
        "centerX": 63488,
        "centerZ": 47104
      }
    ]
  },
  {
    "coord": "A7",
    "name": "Iolite Hollow",
    "slug": "iolite-hollow-r48",
    "zone": "CORE",
    "security": "Patrolled Lanes (CORE)",
    "col": 0,
    "row": 6,
    "xMin": 0,
    "zMin": 49152,
    "xMax": 8192,
    "zMax": 57344,
    "sectors": [
      {
        "id": "NW",
        "xMin": 0,
        "zMin": 49152,
        "xMax": 4096,
        "zMax": 53248,
        "centerX": 2048,
        "centerZ": 51200
      },
      {
        "id": "NE",
        "xMin": 4096,
        "zMin": 49152,
        "xMax": 8192,
        "zMax": 53248,
        "centerX": 6144,
        "centerZ": 51200
      },
      {
        "id": "SW",
        "xMin": 0,
        "zMin": 53248,
        "xMax": 4096,
        "zMax": 57344,
        "centerX": 2048,
        "centerZ": 55296
      },
      {
        "id": "SE",
        "xMin": 4096,
        "zMin": 53248,
        "xMax": 8192,
        "zMax": 57344,
        "centerX": 6144,
        "centerZ": 55296
      }
    ]
  },
  {
    "coord": "B7",
    "name": "Juno Belt",
    "slug": "juno-belt-r49",
    "zone": "MID",
    "security": "Outer Lanes (MID)",
    "col": 1,
    "row": 6,
    "xMin": 8192,
    "zMin": 49152,
    "xMax": 16384,
    "zMax": 57344,
    "sectors": [
      {
        "id": "NW",
        "xMin": 8192,
        "zMin": 49152,
        "xMax": 12288,
        "zMax": 53248,
        "centerX": 10240,
        "centerZ": 51200
      },
      {
        "id": "NE",
        "xMin": 12288,
        "zMin": 49152,
        "xMax": 16384,
        "zMax": 53248,
        "centerX": 14336,
        "centerZ": 51200
      },
      {
        "id": "SW",
        "xMin": 8192,
        "zMin": 53248,
        "xMax": 12288,
        "zMax": 57344,
        "centerX": 10240,
        "centerZ": 55296
      },
      {
        "id": "SE",
        "xMin": 12288,
        "zMin": 53248,
        "xMax": 16384,
        "zMax": 57344,
        "centerX": 14336,
        "centerZ": 55296
      }
    ]
  },
  {
    "coord": "C7",
    "name": "Karst March",
    "slug": "karst-march-r50",
    "zone": "MID",
    "security": "Outer Lanes (MID)",
    "col": 2,
    "row": 6,
    "xMin": 16384,
    "zMin": 49152,
    "xMax": 24576,
    "zMax": 57344,
    "sectors": [
      {
        "id": "NW",
        "xMin": 16384,
        "zMin": 49152,
        "xMax": 20480,
        "zMax": 53248,
        "centerX": 18432,
        "centerZ": 51200
      },
      {
        "id": "NE",
        "xMin": 20480,
        "zMin": 49152,
        "xMax": 24576,
        "zMax": 53248,
        "centerX": 22528,
        "centerZ": 51200
      },
      {
        "id": "SW",
        "xMin": 16384,
        "zMin": 53248,
        "xMax": 20480,
        "zMax": 57344,
        "centerX": 18432,
        "centerZ": 55296
      },
      {
        "id": "SE",
        "xMin": 20480,
        "zMin": 53248,
        "xMax": 24576,
        "zMax": 57344,
        "centerX": 22528,
        "centerZ": 55296
      }
    ]
  },
  {
    "coord": "D7",
    "name": "Loam Crown",
    "slug": "loam-crown-r51",
    "zone": "FRONTIER",
    "security": "Frontier (FRONTIER)",
    "col": 3,
    "row": 6,
    "xMin": 24576,
    "zMin": 49152,
    "xMax": 32768,
    "zMax": 57344,
    "sectors": [
      {
        "id": "NW",
        "xMin": 24576,
        "zMin": 49152,
        "xMax": 28672,
        "zMax": 53248,
        "centerX": 26624,
        "centerZ": 51200
      },
      {
        "id": "NE",
        "xMin": 28672,
        "zMin": 49152,
        "xMax": 32768,
        "zMax": 53248,
        "centerX": 30720,
        "centerZ": 51200
      },
      {
        "id": "SW",
        "xMin": 24576,
        "zMin": 53248,
        "xMax": 28672,
        "zMax": 57344,
        "centerX": 26624,
        "centerZ": 55296
      },
      {
        "id": "SE",
        "xMin": 28672,
        "zMin": 53248,
        "xMax": 32768,
        "zMax": 57344,
        "centerX": 30720,
        "centerZ": 55296
      }
    ]
  },
  {
    "coord": "E7",
    "name": "Murk Cluster",
    "slug": "murk-cluster-r52",
    "zone": "NULL",
    "security": "Wild Drift (NULL)",
    "col": 4,
    "row": 6,
    "xMin": 32768,
    "zMin": 49152,
    "xMax": 40960,
    "zMax": 57344,
    "sectors": [
      {
        "id": "NW",
        "xMin": 32768,
        "zMin": 49152,
        "xMax": 36864,
        "zMax": 53248,
        "centerX": 34816,
        "centerZ": 51200
      },
      {
        "id": "NE",
        "xMin": 36864,
        "zMin": 49152,
        "xMax": 40960,
        "zMax": 53248,
        "centerX": 38912,
        "centerZ": 51200
      },
      {
        "id": "SW",
        "xMin": 32768,
        "zMin": 53248,
        "xMax": 36864,
        "zMax": 57344,
        "centerX": 34816,
        "centerZ": 55296
      },
      {
        "id": "SE",
        "xMin": 36864,
        "zMin": 53248,
        "xMax": 40960,
        "zMax": 57344,
        "centerX": 38912,
        "centerZ": 55296
      }
    ]
  },
  {
    "coord": "F7",
    "name": "Nephele Coil",
    "slug": "nephele-coil-r53",
    "zone": "FRONTIER",
    "security": "Frontier (FRONTIER)",
    "col": 5,
    "row": 6,
    "xMin": 40960,
    "zMin": 49152,
    "xMax": 49152,
    "zMax": 57344,
    "sectors": [
      {
        "id": "NW",
        "xMin": 40960,
        "zMin": 49152,
        "xMax": 45056,
        "zMax": 53248,
        "centerX": 43008,
        "centerZ": 51200
      },
      {
        "id": "NE",
        "xMin": 45056,
        "zMin": 49152,
        "xMax": 49152,
        "zMax": 53248,
        "centerX": 47104,
        "centerZ": 51200
      },
      {
        "id": "SW",
        "xMin": 40960,
        "zMin": 53248,
        "xMax": 45056,
        "zMax": 57344,
        "centerX": 43008,
        "centerZ": 55296
      },
      {
        "id": "SE",
        "xMin": 45056,
        "zMin": 53248,
        "xMax": 49152,
        "zMax": 57344,
        "centerX": 47104,
        "centerZ": 55296
      }
    ]
  },
  {
    "coord": "G7",
    "name": "Onyx Reach",
    "slug": "onyx-reach-r54",
    "zone": "NULL",
    "security": "Wild Drift (NULL)",
    "col": 6,
    "row": 6,
    "xMin": 49152,
    "zMin": 49152,
    "xMax": 57344,
    "zMax": 57344,
    "sectors": [
      {
        "id": "NW",
        "xMin": 49152,
        "zMin": 49152,
        "xMax": 53248,
        "zMax": 53248,
        "centerX": 51200,
        "centerZ": 51200
      },
      {
        "id": "NE",
        "xMin": 53248,
        "zMin": 49152,
        "xMax": 57344,
        "zMax": 53248,
        "centerX": 55296,
        "centerZ": 51200
      },
      {
        "id": "SW",
        "xMin": 49152,
        "zMin": 53248,
        "xMax": 53248,
        "zMax": 57344,
        "centerX": 51200,
        "centerZ": 55296
      },
      {
        "id": "SE",
        "xMin": 53248,
        "zMin": 53248,
        "xMax": 57344,
        "zMax": 57344,
        "centerX": 55296,
        "centerZ": 55296
      }
    ]
  },
  {
    "coord": "H7",
    "name": "Pallid Veil",
    "slug": "pallid-veil-r55",
    "zone": "NULL",
    "security": "Wild Drift (NULL)",
    "col": 7,
    "row": 6,
    "xMin": 57344,
    "zMin": 49152,
    "xMax": 65536,
    "zMax": 57344,
    "sectors": [
      {
        "id": "NW",
        "xMin": 57344,
        "zMin": 49152,
        "xMax": 61440,
        "zMax": 53248,
        "centerX": 59392,
        "centerZ": 51200
      },
      {
        "id": "NE",
        "xMin": 61440,
        "zMin": 49152,
        "xMax": 65536,
        "zMax": 53248,
        "centerX": 63488,
        "centerZ": 51200
      },
      {
        "id": "SW",
        "xMin": 57344,
        "zMin": 53248,
        "xMax": 61440,
        "zMax": 57344,
        "centerX": 59392,
        "centerZ": 55296
      },
      {
        "id": "SE",
        "xMin": 61440,
        "zMin": 53248,
        "xMax": 65536,
        "zMax": 57344,
        "centerX": 63488,
        "centerZ": 55296
      }
    ]
  },
  {
    "coord": "A8",
    "name": "Rann Throne",
    "slug": "rann-throne-r56",
    "zone": "CORE",
    "security": "Patrolled Lanes (CORE)",
    "col": 0,
    "row": 7,
    "xMin": 0,
    "zMin": 57344,
    "xMax": 8192,
    "zMax": 65536,
    "sectors": [
      {
        "id": "NW",
        "xMin": 0,
        "zMin": 57344,
        "xMax": 4096,
        "zMax": 61440,
        "centerX": 2048,
        "centerZ": 59392
      },
      {
        "id": "NE",
        "xMin": 4096,
        "zMin": 57344,
        "xMax": 8192,
        "zMax": 61440,
        "centerX": 6144,
        "centerZ": 59392
      },
      {
        "id": "SW",
        "xMin": 0,
        "zMin": 61440,
        "xMax": 4096,
        "zMax": 65536,
        "centerX": 2048,
        "centerZ": 63488
      },
      {
        "id": "SE",
        "xMin": 4096,
        "zMin": 61440,
        "xMax": 8192,
        "zMax": 65536,
        "centerX": 6144,
        "centerZ": 63488
      }
    ]
  },
  {
    "coord": "B8",
    "name": "Sere Glade",
    "slug": "sere-glade-r57",
    "zone": "CORE",
    "security": "Patrolled Lanes (CORE)",
    "col": 1,
    "row": 7,
    "xMin": 8192,
    "zMin": 57344,
    "xMax": 16384,
    "zMax": 65536,
    "sectors": [
      {
        "id": "NW",
        "xMin": 8192,
        "zMin": 57344,
        "xMax": 12288,
        "zMax": 61440,
        "centerX": 10240,
        "centerZ": 59392
      },
      {
        "id": "NE",
        "xMin": 12288,
        "zMin": 57344,
        "xMax": 16384,
        "zMax": 61440,
        "centerX": 14336,
        "centerZ": 59392
      },
      {
        "id": "SW",
        "xMin": 8192,
        "zMin": 61440,
        "xMax": 12288,
        "zMax": 65536,
        "centerX": 10240,
        "centerZ": 63488
      },
      {
        "id": "SE",
        "xMin": 12288,
        "zMin": 61440,
        "xMax": 16384,
        "zMax": 65536,
        "centerX": 14336,
        "centerZ": 63488
      }
    ]
  },
  {
    "coord": "C8",
    "name": "Tang Drift",
    "slug": "tang-drift-r58",
    "zone": "MID",
    "security": "Outer Lanes (MID)",
    "col": 2,
    "row": 7,
    "xMin": 16384,
    "zMin": 57344,
    "xMax": 24576,
    "zMax": 65536,
    "sectors": [
      {
        "id": "NW",
        "xMin": 16384,
        "zMin": 57344,
        "xMax": 20480,
        "zMax": 61440,
        "centerX": 18432,
        "centerZ": 59392
      },
      {
        "id": "NE",
        "xMin": 20480,
        "zMin": 57344,
        "xMax": 24576,
        "zMax": 61440,
        "centerX": 22528,
        "centerZ": 59392
      },
      {
        "id": "SW",
        "xMin": 16384,
        "zMin": 61440,
        "xMax": 20480,
        "zMax": 65536,
        "centerX": 18432,
        "centerZ": 63488
      },
      {
        "id": "SE",
        "xMin": 20480,
        "zMin": 61440,
        "xMax": 24576,
        "zMax": 65536,
        "centerX": 22528,
        "centerZ": 63488
      }
    ]
  },
  {
    "coord": "D8",
    "name": "Volt Verge",
    "slug": "volt-verge-r59",
    "zone": "FRONTIER",
    "security": "Frontier (FRONTIER)",
    "col": 3,
    "row": 7,
    "xMin": 24576,
    "zMin": 57344,
    "xMax": 32768,
    "zMax": 65536,
    "sectors": [
      {
        "id": "NW",
        "xMin": 24576,
        "zMin": 57344,
        "xMax": 28672,
        "zMax": 61440,
        "centerX": 26624,
        "centerZ": 59392
      },
      {
        "id": "NE",
        "xMin": 28672,
        "zMin": 57344,
        "xMax": 32768,
        "zMax": 61440,
        "centerX": 30720,
        "centerZ": 59392
      },
      {
        "id": "SW",
        "xMin": 24576,
        "zMin": 61440,
        "xMax": 28672,
        "zMax": 65536,
        "centerX": 26624,
        "centerZ": 63488
      },
      {
        "id": "SE",
        "xMin": 28672,
        "zMin": 61440,
        "xMax": 32768,
        "zMax": 65536,
        "centerX": 30720,
        "centerZ": 63488
      }
    ]
  },
  {
    "coord": "E8",
    "name": "Wisp Pale",
    "slug": "wisp-pale-r60",
    "zone": "FRONTIER",
    "security": "Frontier (FRONTIER)",
    "col": 4,
    "row": 7,
    "xMin": 32768,
    "zMin": 57344,
    "xMax": 40960,
    "zMax": 65536,
    "sectors": [
      {
        "id": "NW",
        "xMin": 32768,
        "zMin": 57344,
        "xMax": 36864,
        "zMax": 61440,
        "centerX": 34816,
        "centerZ": 59392
      },
      {
        "id": "NE",
        "xMin": 36864,
        "zMin": 57344,
        "xMax": 40960,
        "zMax": 61440,
        "centerX": 38912,
        "centerZ": 59392
      },
      {
        "id": "SW",
        "xMin": 32768,
        "zMin": 61440,
        "xMax": 36864,
        "zMax": 65536,
        "centerX": 34816,
        "centerZ": 63488
      },
      {
        "id": "SE",
        "xMin": 36864,
        "zMin": 61440,
        "xMax": 40960,
        "zMax": 65536,
        "centerX": 38912,
        "centerZ": 63488
      }
    ]
  },
  {
    "coord": "F8",
    "name": "Yew Spire",
    "slug": "yew-spire-r61",
    "zone": "NULL",
    "security": "Wild Drift (NULL)",
    "col": 5,
    "row": 7,
    "xMin": 40960,
    "zMin": 57344,
    "xMax": 49152,
    "zMax": 65536,
    "sectors": [
      {
        "id": "NW",
        "xMin": 40960,
        "zMin": 57344,
        "xMax": 45056,
        "zMax": 61440,
        "centerX": 43008,
        "centerZ": 59392
      },
      {
        "id": "NE",
        "xMin": 45056,
        "zMin": 57344,
        "xMax": 49152,
        "zMax": 61440,
        "centerX": 47104,
        "centerZ": 59392
      },
      {
        "id": "SW",
        "xMin": 40960,
        "zMin": 61440,
        "xMax": 45056,
        "zMax": 65536,
        "centerX": 43008,
        "centerZ": 63488
      },
      {
        "id": "SE",
        "xMin": 45056,
        "zMin": 61440,
        "xMax": 49152,
        "zMax": 65536,
        "centerX": 47104,
        "centerZ": 63488
      }
    ]
  },
  {
    "coord": "G8",
    "name": "Cinder Shoal",
    "slug": "cinder-shoal-r62",
    "zone": "NULL",
    "security": "Wild Drift (NULL)",
    "col": 6,
    "row": 7,
    "xMin": 49152,
    "zMin": 57344,
    "xMax": 57344,
    "zMax": 65536,
    "sectors": [
      {
        "id": "NW",
        "xMin": 49152,
        "zMin": 57344,
        "xMax": 53248,
        "zMax": 61440,
        "centerX": 51200,
        "centerZ": 59392
      },
      {
        "id": "NE",
        "xMin": 53248,
        "zMin": 57344,
        "xMax": 57344,
        "zMax": 61440,
        "centerX": 55296,
        "centerZ": 59392
      },
      {
        "id": "SW",
        "xMin": 49152,
        "zMin": 61440,
        "xMax": 53248,
        "zMax": 65536,
        "centerX": 51200,
        "centerZ": 63488
      },
      {
        "id": "SE",
        "xMin": 53248,
        "zMin": 61440,
        "xMax": 57344,
        "zMax": 65536,
        "centerX": 55296,
        "centerZ": 63488
      }
    ]
  },
  {
    "coord": "H8",
    "name": "Halcyon March",
    "slug": "halcyon-march-r63",
    "zone": "NULL",
    "security": "Wild Drift (NULL)",
    "col": 7,
    "row": 7,
    "xMin": 57344,
    "zMin": 57344,
    "xMax": 65536,
    "zMax": 65536,
    "sectors": [
      {
        "id": "NW",
        "xMin": 57344,
        "zMin": 57344,
        "xMax": 61440,
        "zMax": 61440,
        "centerX": 59392,
        "centerZ": 59392
      },
      {
        "id": "NE",
        "xMin": 61440,
        "zMin": 57344,
        "xMax": 65536,
        "zMax": 61440,
        "centerX": 63488,
        "centerZ": 59392
      },
      {
        "id": "SW",
        "xMin": 57344,
        "zMin": 61440,
        "xMax": 61440,
        "zMax": 65536,
        "centerX": 59392,
        "centerZ": 63488
      },
      {
        "id": "SE",
        "xMin": 61440,
        "zMin": 61440,
        "xMax": 65536,
        "zMax": 65536,
        "centerX": 63488,
        "centerZ": 63488
      }
    ]
  }
] as const;

export const generatedLocations = [
  {
    "id": "station-ipu-hub-prime-a1",
    "name": "IPU Hub Prime",
    "kind": "station",
    "region": "A1",
    "zone": "CORE",
    "sector": "NW",
    "x": 1306,
    "z": 1397,
    "hidden": false,
    "details": {
      "class": "HUB",
      "owner": "IPU",
      "coordinates": "1306, 1397"
    }
  },
  {
    "id": "station-ipu-outpost-alpha-a2",
    "name": "IPU Outpost Alpha",
    "kind": "station",
    "region": "A2",
    "zone": "CORE",
    "sector": "NW",
    "x": 2845,
    "z": 9816,
    "hidden": false,
    "details": {
      "class": "OUTPOST",
      "owner": "IPU",
      "coordinates": "2845, 9816"
    }
  },
  {
    "id": "station-ipu-hub-secondary-a8",
    "name": "IPU Hub Secondary",
    "kind": "station",
    "region": "A8",
    "zone": "CORE",
    "sector": "SE",
    "x": 4437,
    "z": 61685,
    "hidden": false,
    "details": {
      "coordinates": "4437, 61685"
    }
  },
  {
    "id": "station-ipu-outpost-beta-d8",
    "name": "IPU Outpost Beta",
    "kind": "station",
    "region": "D8",
    "zone": "FRONTIER",
    "sector": "NW",
    "x": 28638,
    "z": 61028,
    "hidden": false,
    "details": {
      "coordinates": "28638, 61028"
    }
  },
  {
    "id": "station-ipu-outpost-gamma-h8",
    "name": "IPU Outpost Gamma",
    "kind": "station",
    "region": "H8",
    "zone": "NULL",
    "sector": "SW",
    "x": 58023,
    "z": 62073,
    "hidden": false,
    "details": {
      "coordinates": "58023, 62073"
    }
  },
  {
    "id": "planet-cinderveil-e6",
    "name": "Cinderveil",
    "kind": "planet",
    "region": "E6",
    "zone": "FRONTIER",
    "sector": "NW",
    "x": 36500,
    "z": 44800,
    "hidden": false,
    "details": {
      "type": "Rocky (Mars-like)",
      "coordinates": "36500, 44800"
    },
    "resources": [
      "Raw Iron Ore",
      "Carbon Deposit",
      "Oxidizer Salt",
      "Lodestone Ore",
      "Phosphate Rock",
      "Potash Salt",
      "Tomato Seeds (Fruiting)"
    ]
  },
  {
    "id": "planet-korrhast-g7",
    "name": "Korrhast",
    "kind": "planet",
    "region": "G7",
    "zone": "NULL",
    "sector": "SW",
    "x": 51500,
    "z": 55500,
    "hidden": false,
    "details": {
      "type": "Frozen",
      "coordinates": "51500, 55500"
    },
    "resources": [
      "Raw Titanium Ore",
      "Lodestone Ore",
      "Cryo-Salt",
      "Ferro-Silicate",
      "Grain Seeds"
    ]
  },
  {
    "id": "planet-palewake-b1",
    "name": "Palewake",
    "kind": "planet",
    "region": "B1",
    "zone": "CORE",
    "sector": "NE",
    "x": 14200,
    "z": 3400,
    "hidden": false,
    "details": {
      "type": "Frozen",
      "coordinates": "14200, 3400"
    },
    "resources": [
      "Raw Titanium Ore",
      "Lodestone Ore",
      "Cryo-Salt",
      "Ferro-Silicate",
      "Grain Seeds"
    ]
  },
  {
    "id": "planet-rustfall-a2",
    "name": "Rustfall",
    "kind": "planet",
    "region": "A2",
    "zone": "CORE",
    "sector": "NE",
    "x": 6555,
    "z": 11549,
    "hidden": false,
    "details": {
      "type": "Rocky (Mars-like)",
      "coordinates": "6555, 11549"
    },
    "resources": [
      "Raw Iron Ore",
      "Carbon Deposit",
      "Oxidizer Salt",
      "Lodestone Ore",
      "Phosphate Rock",
      "Potash Salt",
      "Tomato Seeds (Fruiting)"
    ]
  },
  {
    "id": "belt-hub-prime-quartz-field-a1",
    "name": "Hub Prime Quartz Field",
    "kind": "belt",
    "region": "A1",
    "zone": "CORE",
    "sector": "NW",
    "x": 2136,
    "z": 2085,
    "hidden": false,
    "details": {
      "radius": "600",
      "density": "0.55",
      "coordinates": "2136, 2085"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore"
    ],
    "radius": 600,
    "density": 0.55
  },
  {
    "id": "belt-asteroid-belt-a2",
    "name": "ASTEROID BELT",
    "kind": "belt",
    "region": "A2",
    "zone": "CORE",
    "sector": "SE",
    "x": 6004,
    "z": 15372,
    "hidden": false,
    "details": {
      "radius": "600",
      "density": "0.5",
      "coordinates": "6004, 15372"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore"
    ],
    "radius": 600,
    "density": 0.5
  },
  {
    "id": "belt-asteroid-belt-a4",
    "name": "ASTEROID BELT",
    "kind": "belt",
    "region": "A4",
    "zone": "MID",
    "sector": "NE",
    "x": 4704,
    "z": 27689,
    "hidden": false,
    "details": {
      "radius": "600",
      "density": "0.5",
      "coordinates": "4704, 27689"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore",
      "Raw Titanium Ore"
    ],
    "radius": 600,
    "density": 0.5
  },
  {
    "id": "belt-asteroid-belt-a5",
    "name": "ASTEROID BELT",
    "kind": "belt",
    "region": "A5",
    "zone": "MID",
    "sector": "SE",
    "x": 4262,
    "z": 39926,
    "hidden": false,
    "details": {
      "radius": "600",
      "density": "0.5",
      "coordinates": "4262, 39926"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore",
      "Raw Titanium Ore"
    ],
    "radius": 600,
    "density": 0.5
  },
  {
    "id": "belt-asteroid-belt-a7",
    "name": "ASTEROID BELT",
    "kind": "belt",
    "region": "A7",
    "zone": "CORE",
    "sector": "NE",
    "x": 6597,
    "z": 51809,
    "hidden": false,
    "details": {
      "radius": "900",
      "density": "0.7",
      "coordinates": "6597, 51809"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore"
    ],
    "radius": 900,
    "density": 0.7
  },
  {
    "id": "belt-asteroid-belt-b1",
    "name": "ASTEROID BELT",
    "kind": "belt",
    "region": "B1",
    "zone": "CORE",
    "sector": "SE",
    "x": 12364,
    "z": 4579,
    "hidden": false,
    "details": {
      "radius": "1200",
      "density": "0.9",
      "coordinates": "12364, 4579"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore"
    ],
    "radius": 1200,
    "density": 0.9
  },
  {
    "id": "belt-asteroid-belt-b1",
    "name": "ASTEROID BELT",
    "kind": "belt",
    "region": "B1",
    "zone": "CORE",
    "sector": "SE",
    "x": 16017,
    "z": 6926,
    "hidden": false,
    "details": {
      "radius": "600",
      "density": "0.5",
      "coordinates": "16017, 6926"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore"
    ],
    "radius": 600,
    "density": 0.5
  },
  {
    "id": "belt-asteroid-belt-b2",
    "name": "ASTEROID BELT",
    "kind": "belt",
    "region": "B2",
    "zone": "CORE",
    "sector": "SW",
    "x": 11185,
    "z": 13286,
    "hidden": false,
    "details": {
      "radius": "600",
      "density": "0.5",
      "coordinates": "11185, 13286"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore"
    ],
    "radius": 600,
    "density": 0.5
  },
  {
    "id": "belt-asteroid-belt-b4",
    "name": "ASTEROID BELT",
    "kind": "belt",
    "region": "B4",
    "zone": "MID",
    "sector": "SW",
    "x": 11932,
    "z": 28774,
    "hidden": false,
    "details": {
      "radius": "200",
      "density": "1",
      "coordinates": "11932, 28774"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore",
      "Raw Titanium Ore"
    ],
    "radius": 200,
    "density": 1
  },
  {
    "id": "belt-asteroid-belt-b8",
    "name": "ASTEROID BELT",
    "kind": "belt",
    "region": "B8",
    "zone": "CORE",
    "sector": "SE",
    "x": 12621,
    "z": 63870,
    "hidden": false,
    "details": {
      "radius": "600",
      "density": "0.5",
      "coordinates": "12621, 63870"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore"
    ],
    "radius": 600,
    "density": 0.5
  },
  {
    "id": "belt-asteroid-belt-c2",
    "name": "ASTEROID BELT",
    "kind": "belt",
    "region": "C2",
    "zone": "MID",
    "sector": "NE",
    "x": 21932,
    "z": 10809,
    "hidden": false,
    "details": {
      "radius": "600",
      "density": "0.5",
      "coordinates": "21932, 10809"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore",
      "Raw Titanium Ore"
    ],
    "radius": 600,
    "density": 0.5
  },
  {
    "id": "belt-asteroid-belt-c3",
    "name": "ASTEROID BELT",
    "kind": "belt",
    "region": "C3",
    "zone": "MID",
    "sector": "SW",
    "x": 19866,
    "z": 22374,
    "hidden": false,
    "details": {
      "radius": "600",
      "density": "0.5",
      "coordinates": "19866, 22374"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore",
      "Raw Titanium Ore"
    ],
    "radius": 600,
    "density": 0.5
  },
  {
    "id": "belt-asteroid-belt-c3",
    "name": "ASTEROID BELT",
    "kind": "belt",
    "region": "C3",
    "zone": "MID",
    "sector": "NW",
    "x": 19935,
    "z": 19277,
    "hidden": false,
    "details": {
      "radius": "750",
      "density": "0.5",
      "coordinates": "19935, 19277"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore",
      "Raw Titanium Ore"
    ],
    "radius": 750,
    "density": 0.5
  },
  {
    "id": "belt-asteroid-belt-c4",
    "name": "ASTEROID BELT",
    "kind": "belt",
    "region": "C4",
    "zone": "MID",
    "sector": "SW",
    "x": 19324,
    "z": 29503,
    "hidden": false,
    "details": {
      "radius": "1800",
      "density": "0.99",
      "coordinates": "19324, 29503"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore",
      "Raw Titanium Ore"
    ],
    "radius": 1800,
    "density": 0.99
  },
  {
    "id": "belt-asteroid-belt-c5",
    "name": "ASTEROID BELT",
    "kind": "belt",
    "region": "C5",
    "zone": "MID",
    "sector": "SE",
    "x": 23796,
    "z": 37655,
    "hidden": false,
    "details": {
      "radius": "600",
      "density": "0.5",
      "coordinates": "23796, 37655"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore",
      "Raw Titanium Ore"
    ],
    "radius": 600,
    "density": 0.5
  },
  {
    "id": "belt-asteroid-belt-c6",
    "name": "ASTEROID BELT",
    "kind": "belt",
    "region": "C6",
    "zone": "MID",
    "sector": "NW",
    "x": 18765,
    "z": 43948,
    "hidden": false,
    "details": {
      "radius": "600",
      "density": "0.5",
      "coordinates": "18765, 43948"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore",
      "Raw Titanium Ore"
    ],
    "radius": 600,
    "density": 0.5
  },
  {
    "id": "belt-asteroid-belt-c7",
    "name": "ASTEROID BELT",
    "kind": "belt",
    "region": "C7",
    "zone": "MID",
    "sector": "SE",
    "x": 21587,
    "z": 53353,
    "hidden": false,
    "details": {
      "radius": "600",
      "density": "0.5",
      "coordinates": "21587, 53353"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore",
      "Raw Titanium Ore"
    ],
    "radius": 600,
    "density": 0.5
  },
  {
    "id": "belt-asteroid-belt-d2",
    "name": "ASTEROID BELT",
    "kind": "belt",
    "region": "D2",
    "zone": "MID",
    "sector": "NE",
    "x": 28865,
    "z": 8945,
    "hidden": false,
    "details": {
      "radius": "600",
      "density": "0.5",
      "coordinates": "28865, 8945"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore",
      "Raw Titanium Ore"
    ],
    "radius": 600,
    "density": 0.5
  },
  {
    "id": "belt-asteroid-belt-d3",
    "name": "ASTEROID BELT",
    "kind": "belt",
    "region": "D3",
    "zone": "FRONTIER",
    "sector": null,
    "x": null,
    "z": null,
    "hidden": true,
    "details": {
      "radius": "1600",
      "density": "0.99",
      "coordinates": "(frontier/wild - location not listed)"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore",
      "Raw Titanium Ore",
      "Raw Platinum Ore"
    ],
    "radius": 1600,
    "density": 0.99
  },
  {
    "id": "belt-asteroid-belt-d5",
    "name": "ASTEROID BELT",
    "kind": "belt",
    "region": "D5",
    "zone": "FRONTIER",
    "sector": null,
    "x": null,
    "z": null,
    "hidden": true,
    "details": {
      "radius": "600",
      "density": "0.5",
      "coordinates": "(frontier/wild - location not listed)"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore",
      "Raw Titanium Ore",
      "Raw Platinum Ore"
    ],
    "radius": 600,
    "density": 0.5
  },
  {
    "id": "belt-asteroid-belt-d6",
    "name": "ASTEROID BELT",
    "kind": "belt",
    "region": "D6",
    "zone": "FRONTIER",
    "sector": null,
    "x": null,
    "z": null,
    "hidden": true,
    "details": {
      "radius": "600",
      "density": "0.5",
      "coordinates": "(frontier/wild - location not listed)"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore",
      "Raw Titanium Ore",
      "Raw Platinum Ore"
    ],
    "radius": 600,
    "density": 0.5
  },
  {
    "id": "belt-asteroid-belt-d8",
    "name": "ASTEROID BELT",
    "kind": "belt",
    "region": "D8",
    "zone": "FRONTIER",
    "sector": null,
    "x": null,
    "z": null,
    "hidden": true,
    "details": {
      "radius": "600",
      "density": "0.5",
      "coordinates": "(frontier/wild - location not listed)"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore",
      "Raw Titanium Ore",
      "Raw Platinum Ore"
    ],
    "radius": 600,
    "density": 0.5
  },
  {
    "id": "belt-asteroid-belt-e2",
    "name": "ASTEROID BELT",
    "kind": "belt",
    "region": "E2",
    "zone": "MID",
    "sector": "NW",
    "x": 34805,
    "z": 11842,
    "hidden": false,
    "details": {
      "radius": "600",
      "density": "0.5",
      "coordinates": "34805, 11842"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore",
      "Raw Titanium Ore"
    ],
    "radius": 600,
    "density": 0.5
  },
  {
    "id": "belt-asteroid-belt-e4",
    "name": "ASTEROID BELT",
    "kind": "belt",
    "region": "E4",
    "zone": "FRONTIER",
    "sector": null,
    "x": null,
    "z": null,
    "hidden": true,
    "details": {
      "radius": "600",
      "density": "0.5",
      "coordinates": "(frontier/wild - location not listed)"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore",
      "Raw Titanium Ore",
      "Raw Platinum Ore"
    ],
    "radius": 600,
    "density": 0.5
  },
  {
    "id": "belt-asteroid-belt-f1",
    "name": "ASTEROID BELT",
    "kind": "belt",
    "region": "F1",
    "zone": "FRONTIER",
    "sector": null,
    "x": null,
    "z": null,
    "hidden": true,
    "details": {
      "radius": "600",
      "density": "0.5",
      "coordinates": "(frontier/wild - location not listed)"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore",
      "Raw Titanium Ore",
      "Raw Platinum Ore"
    ],
    "radius": 600,
    "density": 0.5
  },
  {
    "id": "belt-asteroid-belt-f2",
    "name": "ASTEROID BELT",
    "kind": "belt",
    "region": "F2",
    "zone": "MID",
    "sector": "SE",
    "x": 45389,
    "z": 12791,
    "hidden": false,
    "details": {
      "radius": "600",
      "density": "0.5",
      "coordinates": "45389, 12791"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore",
      "Raw Titanium Ore"
    ],
    "radius": 600,
    "density": 0.5
  },
  {
    "id": "belt-asteroid-belt-f5",
    "name": "ASTEROID BELT",
    "kind": "belt",
    "region": "F5",
    "zone": "FRONTIER",
    "sector": null,
    "x": null,
    "z": null,
    "hidden": true,
    "details": {
      "radius": "600",
      "density": "0.5",
      "coordinates": "(frontier/wild - location not listed)"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore",
      "Raw Titanium Ore",
      "Raw Platinum Ore"
    ],
    "radius": 600,
    "density": 0.5
  },
  {
    "id": "belt-asteroid-belt-f6",
    "name": "ASTEROID BELT",
    "kind": "belt",
    "region": "F6",
    "zone": "FRONTIER",
    "sector": null,
    "x": null,
    "z": null,
    "hidden": true,
    "details": {
      "radius": "600",
      "density": "0.5",
      "coordinates": "(frontier/wild - location not listed)"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore",
      "Raw Titanium Ore",
      "Raw Platinum Ore"
    ],
    "radius": 600,
    "density": 0.5
  },
  {
    "id": "belt-asteroid-belt-f7",
    "name": "ASTEROID BELT",
    "kind": "belt",
    "region": "F7",
    "zone": "FRONTIER",
    "sector": null,
    "x": null,
    "z": null,
    "hidden": true,
    "details": {
      "radius": "600",
      "density": "0.5",
      "coordinates": "(frontier/wild - location not listed)"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore",
      "Raw Titanium Ore",
      "Raw Platinum Ore"
    ],
    "radius": 600,
    "density": 0.5
  },
  {
    "id": "belt-asteroid-belt-f8",
    "name": "ASTEROID BELT",
    "kind": "belt",
    "region": "F8",
    "zone": "NULL",
    "sector": null,
    "x": null,
    "z": null,
    "hidden": true,
    "details": {
      "radius": "600",
      "density": "0.5",
      "coordinates": "(frontier/wild - location not listed)"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore",
      "Raw Titanium Ore",
      "Raw Platinum Ore",
      "Raw Iridium Ore"
    ],
    "radius": 600,
    "density": 0.5
  },
  {
    "id": "belt-asteroid-belt-g3",
    "name": "ASTEROID BELT",
    "kind": "belt",
    "region": "G3",
    "zone": "FRONTIER",
    "sector": null,
    "x": null,
    "z": null,
    "hidden": true,
    "details": {
      "radius": "600",
      "density": "0.5",
      "coordinates": "(frontier/wild - location not listed)"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore",
      "Raw Titanium Ore",
      "Raw Platinum Ore"
    ],
    "radius": 600,
    "density": 0.5
  },
  {
    "id": "belt-asteroid-belt-g4",
    "name": "ASTEROID BELT",
    "kind": "belt",
    "region": "G4",
    "zone": "NULL",
    "sector": null,
    "x": null,
    "z": null,
    "hidden": true,
    "details": {
      "radius": "600",
      "density": "0.5",
      "coordinates": "(frontier/wild - location not listed)"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore",
      "Raw Titanium Ore",
      "Raw Platinum Ore",
      "Raw Iridium Ore"
    ],
    "radius": 600,
    "density": 0.5
  },
  {
    "id": "belt-asteroid-belt-g4",
    "name": "ASTEROID BELT",
    "kind": "belt",
    "region": "G4",
    "zone": "NULL",
    "sector": null,
    "x": null,
    "z": null,
    "hidden": true,
    "details": {
      "radius": "600",
      "density": "0.5",
      "coordinates": "(frontier/wild - location not listed)"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore",
      "Raw Titanium Ore",
      "Raw Platinum Ore",
      "Raw Iridium Ore"
    ],
    "radius": 600,
    "density": 0.5
  },
  {
    "id": "belt-asteroid-belt-g4",
    "name": "ASTEROID BELT",
    "kind": "belt",
    "region": "G4",
    "zone": "NULL",
    "sector": null,
    "x": null,
    "z": null,
    "hidden": true,
    "details": {
      "radius": "1900",
      "density": "0.99",
      "coordinates": "(frontier/wild - location not listed)"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore",
      "Raw Titanium Ore",
      "Raw Platinum Ore",
      "Raw Iridium Ore"
    ],
    "radius": 1900,
    "density": 0.99
  },
  {
    "id": "belt-asteroid-belt-g6",
    "name": "ASTEROID BELT",
    "kind": "belt",
    "region": "G6",
    "zone": "FRONTIER",
    "sector": null,
    "x": null,
    "z": null,
    "hidden": true,
    "details": {
      "radius": "600",
      "density": "0.5",
      "coordinates": "(frontier/wild - location not listed)"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore",
      "Raw Titanium Ore",
      "Raw Platinum Ore"
    ],
    "radius": 600,
    "density": 0.5
  },
  {
    "id": "belt-asteroid-belt-g7",
    "name": "ASTEROID BELT",
    "kind": "belt",
    "region": "G7",
    "zone": "NULL",
    "sector": null,
    "x": null,
    "z": null,
    "hidden": true,
    "details": {
      "radius": "600",
      "density": "0.5",
      "coordinates": "(frontier/wild - location not listed)"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore",
      "Raw Titanium Ore",
      "Raw Platinum Ore",
      "Raw Iridium Ore"
    ],
    "radius": 600,
    "density": 0.5
  },
  {
    "id": "belt-asteroid-belt-g8",
    "name": "ASTEROID BELT",
    "kind": "belt",
    "region": "G8",
    "zone": "NULL",
    "sector": null,
    "x": null,
    "z": null,
    "hidden": true,
    "details": {
      "radius": "1200",
      "density": "0.5",
      "coordinates": "(frontier/wild - location not listed)"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore",
      "Raw Titanium Ore",
      "Raw Platinum Ore",
      "Raw Iridium Ore"
    ],
    "radius": 1200,
    "density": 0.5
  },
  {
    "id": "belt-asteroid-belt-h1",
    "name": "ASTEROID BELT",
    "kind": "belt",
    "region": "H1",
    "zone": "FRONTIER",
    "sector": null,
    "x": null,
    "z": null,
    "hidden": true,
    "details": {
      "radius": "600",
      "density": "0.5",
      "coordinates": "(frontier/wild - location not listed)"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore",
      "Raw Titanium Ore",
      "Raw Platinum Ore"
    ],
    "radius": 600,
    "density": 0.5
  },
  {
    "id": "belt-asteroid-belt-h2",
    "name": "ASTEROID BELT",
    "kind": "belt",
    "region": "H2",
    "zone": "FRONTIER",
    "sector": null,
    "x": null,
    "z": null,
    "hidden": true,
    "details": {
      "radius": "600",
      "density": "0.5",
      "coordinates": "(frontier/wild - location not listed)"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore",
      "Raw Titanium Ore",
      "Raw Platinum Ore"
    ],
    "radius": 600,
    "density": 0.5
  },
  {
    "id": "belt-asteroid-belt-h6",
    "name": "ASTEROID BELT",
    "kind": "belt",
    "region": "H6",
    "zone": "NULL",
    "sector": null,
    "x": null,
    "z": null,
    "hidden": true,
    "details": {
      "radius": "1700",
      "density": "0.99",
      "coordinates": "(frontier/wild - location not listed)"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore",
      "Raw Titanium Ore",
      "Raw Platinum Ore",
      "Raw Iridium Ore"
    ],
    "radius": 1700,
    "density": 0.99
  },
  {
    "id": "belt-asteroid-belt-h7",
    "name": "ASTEROID BELT",
    "kind": "belt",
    "region": "H7",
    "zone": "NULL",
    "sector": null,
    "x": null,
    "z": null,
    "hidden": true,
    "details": {
      "radius": "600",
      "density": "0.5",
      "coordinates": "(frontier/wild - location not listed)"
    },
    "resources": [
      "Raw Iron Ore",
      "Raw Copper Ore",
      "Raw Titanium Ore",
      "Raw Platinum Ore",
      "Raw Iridium Ore"
    ],
    "radius": 600,
    "density": 0.5
  },
  {
    "id": "gate-halcyon-vesper-gate-h8",
    "name": "Halcyon-Vesper Gate",
    "kind": "gate",
    "region": "H8",
    "zone": "NULL",
    "sector": "SW",
    "x": 57743,
    "z": 62374,
    "hidden": false,
    "details": {
      "linksTo": "Vesper-Halcyon Gate",
      "coordinates": "57743, 62374"
    },
    "linksTo": "Vesper-Halcyon Gate"
  },
  {
    "id": "gate-nimbus-vesper-gate-e4",
    "name": "Nimbus-Vesper Gate",
    "kind": "gate",
    "region": "E4",
    "zone": "FRONTIER",
    "sector": "SW",
    "x": 34516,
    "z": 30766,
    "hidden": false,
    "details": {
      "linksTo": "Vesper-Nimbus Gate",
      "coordinates": "34516, 30766"
    },
    "linksTo": "Vesper-Nimbus Gate"
  },
  {
    "id": "gate-ronn-solyn-gate-a8",
    "name": "Ronn-Solyn Gate",
    "kind": "gate",
    "region": "A8",
    "zone": "CORE",
    "sector": "NE",
    "x": 4242,
    "z": 61438,
    "hidden": false,
    "details": {
      "linksTo": "Solyn-Ronn Gate",
      "coordinates": "4242, 61438"
    },
    "linksTo": "Solyn-Ronn Gate"
  },
  {
    "id": "gate-ronn-vesper-gate-a8",
    "name": "Ronn-Vesper Gate",
    "kind": "gate",
    "region": "A8",
    "zone": "CORE",
    "sector": "SE",
    "x": 4704,
    "z": 61875,
    "hidden": false,
    "details": {
      "linksTo": "Vesper-Ronn Gate",
      "coordinates": "4704, 61875"
    },
    "linksTo": "Vesper-Ronn Gate"
  },
  {
    "id": "gate-solyn-ronn-gate-a2",
    "name": "Solyn-Ronn Gate",
    "kind": "gate",
    "region": "A2",
    "zone": "CORE",
    "sector": "NW",
    "x": 3000,
    "z": 10231,
    "hidden": false,
    "details": {
      "linksTo": "Ronn-Solyn Gate",
      "coordinates": "3000, 10231"
    },
    "linksTo": "Ronn-Solyn Gate"
  },
  {
    "id": "gate-solyn-vega-gate-a2",
    "name": "Solyn-Vega Gate",
    "kind": "gate",
    "region": "A2",
    "zone": "CORE",
    "sector": "NW",
    "x": 2704,
    "z": 9393,
    "hidden": false,
    "details": {
      "linksTo": "Vega-Solyn Gate",
      "coordinates": "2704, 9393"
    },
    "linksTo": "Vega-Solyn Gate"
  },
  {
    "id": "gate-vega-solyn-gate-a1",
    "name": "Vega-Solyn Gate",
    "kind": "gate",
    "region": "A1",
    "zone": "CORE",
    "sector": "NW",
    "x": 1333,
    "z": 1918,
    "hidden": false,
    "details": {
      "linksTo": "Solyn-Vega Gate",
      "coordinates": "1333, 1918"
    },
    "linksTo": "Solyn-Vega Gate"
  },
  {
    "id": "gate-vesper-halcyon-gate-d8",
    "name": "Vesper-Halcyon Gate",
    "kind": "gate",
    "region": "D8",
    "zone": "FRONTIER",
    "sector": "NE",
    "x": 29051,
    "z": 61046,
    "hidden": false,
    "details": {
      "linksTo": "Halcyon-Vesper Gate",
      "coordinates": "29051, 61046"
    },
    "linksTo": "Halcyon-Vesper Gate"
  },
  {
    "id": "gate-vesper-nimbus-gate-d8",
    "name": "Vesper-Nimbus Gate",
    "kind": "gate",
    "region": "D8",
    "zone": "FRONTIER",
    "sector": "NE",
    "x": 28791,
    "z": 60771,
    "hidden": false,
    "details": {
      "linksTo": "Nimbus-Vesper Gate",
      "coordinates": "28791, 60771"
    },
    "linksTo": "Nimbus-Vesper Gate"
  },
  {
    "id": "gate-vesper-ronn-gate-d8",
    "name": "Vesper-Ronn Gate",
    "kind": "gate",
    "region": "D8",
    "zone": "FRONTIER",
    "sector": "NW",
    "x": 28308,
    "z": 61052,
    "hidden": false,
    "details": {
      "linksTo": "Ronn-Vesper Gate",
      "coordinates": "28308, 61052"
    },
    "linksTo": "Ronn-Vesper Gate"
  },
  {
    "id": "wreck-the-first-drift-a1",
    "name": "The First Drift",
    "kind": "wreck",
    "region": "A1",
    "zone": "CORE",
    "sector": "NW",
    "x": 1251,
    "z": 1542,
    "hidden": false,
    "details": {
      "coordinates": "1251, 1542"
    }
  },
  {
    "id": "system-veyra-c2",
    "name": "Veyra",
    "kind": "system",
    "region": "C2",
    "zone": "MID",
    "sector": "SE",
    "x": 22000,
    "z": 16000,
    "hidden": false,
    "details": {
      "coordinates": "22000, 16000"
    }
  }
] as const;

export const generatedGatePairs = [
  {
    "a": "gate-halcyon-vesper-gate-h8",
    "b": "gate-vesper-halcyon-gate-d8"
  },
  {
    "a": "gate-nimbus-vesper-gate-e4",
    "b": "gate-vesper-nimbus-gate-d8"
  },
  {
    "a": "gate-ronn-solyn-gate-a8",
    "b": "gate-solyn-ronn-gate-a2"
  },
  {
    "a": "gate-ronn-vesper-gate-a8",
    "b": "gate-vesper-ronn-gate-d8"
  },
  {
    "a": "gate-solyn-vega-gate-a2",
    "b": "gate-vega-solyn-gate-a1"
  }
] as const;

export const generatedOreIndex = [
  {
    "ore": "Raw Copper Ore",
    "minZone": "Patrolled Lanes (CORE)",
    "belts": 41,
    "where": "see belt coords above"
  },
  {
    "ore": "Raw Iridium Ore",
    "minZone": "Wild Drift (NULL)",
    "belts": 8,
    "where": "frontier / wild drift only - locations not listed; explore to find"
  },
  {
    "ore": "Raw Iron Ore",
    "minZone": "Patrolled Lanes (CORE)",
    "belts": 41,
    "where": "see belt coords above"
  },
  {
    "ore": "Raw Platinum Ore",
    "minZone": "Frontier (FRONTIER)",
    "belts": 21,
    "where": "frontier / wild drift only - locations not listed; explore to find"
  },
  {
    "ore": "Raw Titanium Ore",
    "minZone": "Outer Lanes (MID)",
    "belts": 34,
    "where": "see belt coords above"
  }
] as const;
